### ISSUE TITLE
Insertion concurrency not covered

### ISSUE THREAD

**Issue by qidydl** [dotnet/EntityFramework.Docs#1171]
The documentation provides a good example of how to handle concurrent UPDATE scenarios, but not concurrent INSERTs. A failed insert results in a more generic DbUpdateException with no Entities provided to correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649fbab8-b960-6873-14bf-188d14757fee
* Version Independent ID: f5ee3135-54c8-689c-e28b-b203b376bd6f
* Content: [Handling Concurrency Conflicts - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/concurrency)
* Content Source: [entity-framework/core/saving/concurrency.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/concurrency.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by sugarjig** [comment]
I would also like to see an example in docs for handling concurrent INSERTs. Our solution to this is to catch the `DbUpdateException`, then do the following check: `(dbUpdateException.InnerException as SqlException)?.Number == 2601`.

**Comment by Yashuaaa** [comment]
Is this not crazy to you all? The only way to deal with this issue is to "catch an exception". Literally that is the standard solution?

**Comment by MCcoder52** [comment]
There is no concurrency issue with Inserts. Only duplicate key issues.

**Comment by C26000** [comment]
There is concurrency issue with inserts, one that causes duplicate key issues. You may call them by a different name but they are still are problems caused by concurrent saves by different users. EF Core should provide a way to handle this issues. Unfortunately the duplicated key exceptions don't provide info about the entries with conflict as they do in the DbUpdateConcurrencyException, that would help to implement this concurrency control in inserts. They do have plan to add it but apparently it have been pushed multiple times: https://github.com/dotnet/efcore/issues/7829

I had this requirment for one of my projects so I had to implement it using the ChangeTracker.Entries and insert them once each time until I find the entry that causes the duplicated key exception and then resolve de problem. It's a kind of ugly solution but it works... If anyone is interested you can check it here: https://github.com/C26000/SimpleOps/blob/master/SimpleOps/Datos/Contexto.cs in GuardarCambios() method.

**Comment by roji** [comment]
The important point about duplicate key issues is that they're not *necessarily* a concurrency issue; they can very well just be the result of incorrect data entry (duplicate key), buggy code, or various other reasons. This is why EF Core can't throw a DbUpdateConcurrencyException when the database errors with a unique constraint violation.

I'll add a note about this in the concurrency docs which I'm working on at the moment.
