### ISSUE TITLE
EF6: What are the defaults if app.config is missing and code-based configuration isn't provided

### ISSUE THREAD

**Issue by madelson** [dotnet/EntityFramework.Docs#1284]
What happens if I don't set the configuration either in code or in app.config? What are the defaults?

When I install the EF6 package it adds some stuff to app.config; do I need to keep that or is it just specifying the defaults again?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcb983de-7c86-dfeb-6548-dde4a9f17379
* Version Independent ID: 547e9c6a-75e6-da12-f60b-93b767eed3f7
* Content: [Code-based configuration - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/configuring/code-based)
* Content Source: [entity-framework/ef6/fundamentals/configuring/code-based.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/configuring/code-based.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by divega** [comment]
@ajcvickers @bricelam I don't remember what exactly are the defaults now, but I believe in EF6.3 we are going to revisit them as part of the PackageReference support. 

We can use this issue to track reflecting the choices we make in the EF6 docs.

**Comment by bricelam** [comment]
Without an App.Config, EF6 can still find the SQL Server EF6 provider, so that part isn't needed.

The default connection factory for SQL Server uses `.\SQLEXPRESS`, but there is some magic in the NuGet package to detect LocalDB and use it instead if it's present. If you always specify the data source in the connection string, you can remove that part of the App.Config too.
