### ISSUE TITLE
Document switch to standard IAsyncEnumerable<T> as a breaking change

### ISSUE THREAD

**Issue by divega** [dotnet/EntityFramework.Docs#1538]
cc @divega

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d0e044-b0cb-21e2-19c1-2f137da671ac
* Version Independent ID: 1cbedd95-8640-1649-9967-d0ef71633534
* Content: [Breaking changes in EF Core 3.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes)
* Content Source: [entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by powermetal63** [comment]
What "standard"? Does that mean that EF Core 3.0+ cancels .NET Framework support? This sounds like the most breaking change, which should be at the top of the list., so people which are stuck to .NET Framework (can't switch to the "latest and greatest" .Net Core due to legacy reasons/unsupported features) and unluckily decided to use EF Core at least know in advance.

**Comment by BobbyCannon** [comment]
@powermaetal63 I just learned that EF Core 3.1 rolls back to .netstandard 2.0. Woot!
