### ISSUE TITLE
Document creation of CHECK constraints for enum property mappings

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/EntityFramework.Docs#2082]
See https://github.com/dotnet/efcore/issues/15411

**Comment by henrikdahl8240** [comment]
When using this very valuable feature using .Net 5.0 Preview 3, the invocations of `b1.HasCheckConstraint(` in the code generated by Add-Migration makes the compiler to complain that there is no HasCheckContraint method available for b1.
Is the HasCheckConstraint stuff not supported by migrations yet in .Net 5.0 Preview 3?

**Comment by henrikdahl8240** [comment]
How to specify the name for the constraint being generated because the automatically generated name is more than 128 characters long in many of my cases?

Is it for instance possible to invoke `.HasConstraintName` for an enum?

**Comment by roji** [comment]
@henrikdahl8240 can you please open new issues for your problems rather than posting on this one, which is about something different?

Note that HasCheckConstraint accepts a `name` argument to define the constraint name. For your first question, please include a code sample that shows the error in a new issue.

**Comment by roji** [comment]
This is no longer part of EF Core, and should be documented in https://github.com/efcore/EFCore.CheckConstraints.
