### ISSUE TITLE
Example contradicts documentation of naming of auto created fk shaddow properties.

### ISSUE THREAD

**Issue by yeah-boi** [dotnet/EntityFramework.Docs#2116]
In the section "No foreign key property" the rules for naming of the automatically created shaddow fk property are specified.

They are however contradicted by the example in the same section with the following motivation:

"In this example the shadow foreign key is BlogId because prepending the navigation name would be redundant."

The rules are described as follows, but there is no mentioning about this exception there:

`If no foreign key property is found, a shadow foreign key property will be introduced with the name <navigation property name><principal key property name> or <principal entity name><principal key property name> if no navigation is present on the dependent type.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@yeah-boi In this case:
* The navigation name is `Blog`
* The principal key property name is `BlogId`

So following the rules the resultant name would be:
* `<navigation property name><principal key property name>` => `BlogBlogId`
* Or `<principal entity name><principal key property name>` => `BlogBlogId`

The note below is attempting to clarify that because this name contains  `BlogBlog` we remove the redundancy and just use `BlogId`.
