### ISSUE TITLE
Why do you create two contexts?  

### ISSUE THREAD

**Issue by punkouter2018** [dotnet/EntityFramework.Docs#2146]
For the test.. Why not share the context when and add and when you check ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c95e5c7e-882f-76f7-5301-2a5d1ede39d3
* Version Independent ID: 8754aa99-67a7-98ac-a51e-0ba995f96414
* Content: [Testing with InMemory - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory#feedback)
* Content Source: [entity-framework/core/miscellaneous/testing/in-memory.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/in-memory.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@punkouter2018 Because it aligns with the guidance to use a single context instance for a single unit-of-work for the most common use of EF Core which is for web apps where the query is done separately to the update.

In other words, using one context instance usually doesn't match what a web application does. Specifically, the context used for updates will not still be tracking the entities originally queried from the database. The context in test should therefore also not be tracking these entities so that it tests the same behavior as the real app.

**Comment by punkouter2018** [comment]
in other words.. when you read and then you write to something in a web site these are two separate calls and therefore 2 separate contexts ?

**Comment by ajcvickers** [comment]
@punkouter2018 Yes. :-) Your explanation is much more succinct. I shall use it next time I answer this question.

/cc @jonpsmith
