### ISSUE TITLE
Syntax error in lazy loading examples

### ISSUE THREAD

**Issue by tanveerbadar** [dotnet/EntityFramework.Docs#2177]
The lazy loading examples which inject the loader delegate have a syntax error. Since the loader is `Action&lt;object, string&gt;` you cannot say `loader.Load(this, _field)` but must say `loader(this, _field)` instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@tanveerbadar This intentional--see the text and code immediately below:

> The code above uses a Load extension method to make using the delegate a bit cleaner:

```C#
public static class PocoLoadingExtensions
{
    public static TRelated Load<TRelated>(
        this Action<object, string> loader,
        object entity,
        ref TRelated navigationField,
        [CallerMemberName] string navigationName = null)
        where TRelated : class
    {
        loader?.Invoke(entity, navigationName);

        return navigationField;
    }
}
```

**Comment by tanveerbadar** [comment]
May I ask how a syntax error is intentional and by-design? Of course I saw the example after that, and the reason I opened this ticket is to request the error be corrected.

**Comment by ajcvickers** [comment]
@tanveerbadar It's not a syntax error. The reason `LazyLoader.Load(this, ref _blog);` is not compiling for you is that the `Load` method being called here is the one defined below. That's why it says, "The code above uses a Load extension method". You need both pieces of code to make this work.

The reason for the extension method is that calling `loader(this, _field)` with a null `loader` delegate would throw. The extension method allows it to not throw and instead return the current value of the field.

**Comment by tanveerbadar** [comment]
Thank you for the explanation. I now see where I was wrong.
