### ISSUE TITLE
Incorrect comment

### ISSUE THREAD

**Issue by Tommigun1980** [dotnet/EntityFramework.Docs#2353]
"Therefore, it is recommended to keep your DbSet properties non-nullable - allowing you to access them without null checks - and to silence the compiler warnings by explicitly setting them to null with the help of the null-forgiving operator (!):"

Setting them to null? But hey are never null.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@Tommigun1980 the point here is that since the DbSet properties are non-nullable, the compiler will refuse to build the code without initializing them, since it doesn't know they always get late-initialized by EF Core. Therefore, in order to satisfy the compiling, it's possible to force-initialize these properties to null with the null-forgiving operator - null will never actually be visible to any consumer of those properties.

Do you see any issue with the guidance or with the wording?
