### ISSUE TITLE
Document that large/binary data isn't recommended for seeding

### ISSUE THREAD

**Issue by roji** [dotnet/EntityFramework.Docs#2416]
Following https://github.com/dotnet/efcore/issues/21065

**Comment by ntziolis** [comment]
Sry to bring this up again, but the issue was already caused for 1.4Megabytes of data (combined total not single file, each file was ~300KB). If that classifies as large in efcore context (and I understand if it would), please do document what expected amounts of data are that efcore can handle explicitly. As I'd assume most people would not consider either 300KB or 1.4MB large.

**Comment by roji** [comment]
@ntziolis seeding really is meant for small, static data, such as strings/numbers/dates. We definitely do need to document this.
