### ISSUE TITLE
Page lacks version references

### ISSUE THREAD

**Issue by Prinsn** [dotnet/EntityFramework.Docs#2504]
This page refers to a method `CreateInMemoryDatabase` which does not appear to exist or be referenced anywhere outside of a definition in EF7, and this is a page for EF Core.  This page is the only place that Google seems to be able to locate that makes reference to it and EF Core.

There are no using statements in the code snippet, or anything else to direct a user to where this method should exist, or if it has a minimum version.

Looking in our 3.1 EFCore project, not only does that method not exist, neither does the `DbContextOptionsBuilder.UseSqlLite` method, which exists in our 2.2 project.

This page seems to simply lack sufficient information to be useful except as pseudo code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7b56f-7f91-2f15-1fb6-4f481e97534f
* Version Independent ID: 6d9c65c6-f159-b234-48fd-f25da05f0f32
* Content: [Testing with SQLite - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite)
* Content Source: [entity-framework/core/miscellaneous/testing/sqlite.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/sqlite.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
The method `CreateInMemoryDatabase` is defined in the code snippet. It is has no relation with any method defined elsewhere. It is just private static method. You can name it whatever you want. There are not using statement for brevity. Also all IDEs offer import for types. It is also assumed that since this is about testing with EF Core, you have EF Core Sqlite provider installed. There is not minimum version requires since it works with any version of EF Core. The Method `CreateInMemoryDatabase` is not part of EF Core. `DbContextOptionsBuilder.UseSqlLite` method does not exist in EF Core. It never existed. The method is always called `UseSqlite` See [reference documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.sqlitedbcontextoptionsbuilderextensions.usesqlite?view=efcore-3.1#Microsoft_EntityFrameworkCore_SqliteDbContextOptionsBuilderExtensions_UseSqlite_Microsoft_EntityFrameworkCore_DbContextOptionsBuilder_System_Data_Common_DbConnection_System_Action_Microsoft_EntityFrameworkCore_Infrastructure_SqliteDbContextOptionsBuilder__)

UseSqlLite seems to method coming from other package or you defined it in your codebase. Please contact owner of that method if you have any questions.

The sample in current form is appropriate and working correctly.

**Comment by Prinsn** [comment]
Dear god, I apologize for this idiocy.

I didn't see it in the snippet (to the point where I'm citing a 5 minute mandella effect), and searched for it else wise on the page and didn't find anything.
