### ISSUE TITLE
Document ChangeTracker.Clear()

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/EntityFramework.Docs#2524]

**Comment by VaclavElias** [comment]
I am quite happy about this new method which I could use instead of my current implementation.

I am syncing some data around 20,000 - 100,000 which might be already in the database. I do it in batches e.g. 5000 items and I use one context for that so with this hack below I reset after every batch and see significant speed improvements.

![image](https://user-images.githubusercontent.com/4528464/88169466-e8c6a980-cc13-11ea-9595-7c9b478e5ce0.png)

Just for a reference, also on this subject https://stackoverflow.com/questions/55454624/how-to-delete-whole-database-and-reset-the-change-tracker-with-ef-core-using-sql.

Once I tested .NET 5, I will provide an udpate here.
