### ISSUE TITLE
Incomplete method description.

### ISSUE THREAD

**Issue by DarkChocoholicDev** [dotnet/EntityFramework.Docs#2640]
This page is incomplete, failing to include suitable usage notes or even the return value. Some sentences don't even end with a period, suggesting that the content was never finished.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cc59de4-f83e-dc9f-2d1d-00e6dd8b5a6a
* Version Independent ID: 5a6309f7-1ebf-fe14-deca-c3d223877822
* Content: [Database.BeginTransaction Method (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.database.begintransaction?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Data.Entity.Database.BeginTransaction);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.5);k(DevLang-csharp)%26rd%3Dtrue&view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity/Database.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/Database.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
