### ISSUE TITLE
Breaking change to IMethodCallTranslator

### ISSUE THREAD

**Issue by bricelam** [dotnet/EntityFramework.Docs#2694]
PR dotnet/efcore#21935 broke `IMethodCallTranslator`. This break cascades into plugins. If they want to support both 3.1 and 5.0, they will need to maintain two concurrent versions.

I don't think maintaining two versions is necessarily a bad thing--it allows them to also leverage the new null propagation metadata to produce cleaner queries--but we should discuss it as a team.

**Comment by smitpatel** [comment]
@dotnet/efteam - Where should I add this provider/plugin writer affecting change?

**Comment by roji** [comment]
> Where should I add this provider/plugin writer affecting change?

We can put a note in the regular breaking changes page. However, any plugin affected by this is likely to be a provider plugin (e.g. EFCore.PG.NetTopologySuite), since is about method translation. So to me this seems like just another providers-beware, which I don't think we currently put in the breaking changes page.

This is also relevant for the "two versions" question. Since method-translating plugins are (almost?) always bound to a specific provider anyway, they can be sort of considered a modular part of that provider, and therefore advance versions with it. In other words, for EFCore.PG.NetTopologySuite there's a 5.0 version that works with EFCore.PG 5.0 and EFCore 5.0, and there's no real need to maintain two versions...
