### ISSUE TITLE
nullable boolean?

### ISSUE THREAD

**Issue by jaoord** [dotnet/EntityFramework.Docs#2907]
the docs mention a nullable boolean, but the return type is `bool`, not `bool?` (or `Nullable<bool>`)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07a070db-4bac-b894-f44a-9f0bd601281d
* Version Independent ID: e31f861b-2010-a3f0-de4d-ddc5c292c924
* Content: [DbGeography.IsEmpty Property (System.Data.Entity.Spatial)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.spatial.dbgeography.isempty?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity.Spatial/DbGeography.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.Spatial/DbGeography.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by jaoord** [comment]
Weird response. It’s clearly a docs error

**Comment by roji** [comment]
@jaoord it indeed seems to be a docs error - but EF6 as a whole is more or less in archive mode. So we're not spending any time on fixing doc issues for it, but if you'd like to submit a PR fixing this we'll definitely merge it.

**Comment by ajcvickers** [comment]
@jaoord @roji It's a docs error, but it's in the API docs, which are built from the source. So a normal "docs PR" won't help anything here, and a code PR will only help if we re-build the API docs from the source, which might happen, but isn't currently planned. That's why I used the source code message rather than the docs message.

**Comment by smitpatel** [comment]
What is the correct return type here? bool or nullable bool? I can just hand edit the XML for API docs.

**Comment by jaoord** [comment]
bool
