### ISSUE TITLE
Understanding HasDiscriminator.IsComplete() 

### ISSUE THREAD

**Issue by wcrowther** [dotnet/EntityFramework.Docs#2955]
I am porting some code from EF6 and have questions about the section on HasDiscriminator().IsComplete(false). 

The original code in EF6 used default TPH behavior to map a base abstract class and it's derived classes. The desciminator was by default a string value of the derived class name. Also by default convention, a query of the base abstract DbSet would bring back objects of the derived class. If you had a general query of that DbSet for the Abstract base Animal, it would return derived Cats, Dogs, and Rabbits, etc.

EF Core no longer seems to follow this logic and requires derived classes to be opted in. Your documentation states:

> By convention, types that are exposed in DbSet properties on your context are included in the model as entities. Entity types that are specified in the OnModelCreating method are also included, as are any types that are found by recursively exploring the navigation properties of other discovered entity types.

In my case I have a rules engine where I have a base class with derived types for different rules where it opts in all derived classes by default. 

From documentation on HasDiscriminator.IsComplete(false):

> When materializing results from a query, if we come across a discriminator value, which isn't mapped to any entity type in the model, we throw an exception since we don't know how to materialize the results. This error only occurs if your database contains rows with discriminator values, which aren't mapped in the EF model. If you have such data, then you can mark the discriminator mapping in EF Core model as incomplete to indicate that we should always add filter predicate for querying any type in the hierarchy. 

So this looked like a way to provide the old EF6 convention without having to opt-in to every derived class . This does not seem to be case as I receive the error below so it is not clear to me what exactly the documentation means.

> Message=The corresponding CLR type for entity type 'SymbolRule' cannot be instantiated, and there is no derived entity type in the model that corresponds to a concrete CLR type.

Please provide context to help me understand what .IsComplete(false) actually does. I will then add  a bug or feature request for the functionality to automatically return derived classes as it worked in EF6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a10898c5-abee-1843-cfff-b2707f8a079a
* Version Independent ID: d9399618-488e-20b1-f707-35a191b95cc1
* Content: [Inheritance - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance)
* Content Source: [entity-framework/core/modeling/inheritance.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/inheritance.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
IsComplete on a discriminator is only away to let EF know that it will never encounter discriminator values in the database which have not been configured in its model - it does not in any way change how EF discovers entity types, or whether it automatically explores the type hierarchy and adds sub-types to the model. The purpose of IsComplete is to allow EF to make certain optimizations when generating SQL, since we EF can assume it knows about all discriminator values it will ever encounter.

**Comment by ajcvickers** [comment]
@wcrowther EF6 automatically searches for derived types in the same assembly and adds them to the model. By design, EF Core does not do this. Therefore you will need to make sure that there is an explicit call to `modelBuilder.Entity<TEntity>();` for each subtype.

**Comment by wcrowther** [comment]
@roji - Thanks for the additional information.

**Comment by wcrowther** [comment]
@ajcvickers - I can understand that an opt-in mechanism for derived classes makes some sense for the default but it would be nice to see an automatic opt-in feature. The use-case for me is a rules engine table with many rules that all derive from the base class where it would be good to not have to individually register them.

Unless you have a counter argument, I will put in a feature request.

**Comment by ajcvickers** [comment]
@wcrowther We discussed this as a team. We are, in general, against assembly scanning solutions. The main reasons for this are:

- Assembly scanning can get very slow for some assemblies with many generated types.
- Assembly scanning can have side effects caused by loading the types. This was particularly problematic on .NET Framework, where the security model could lead to a variety of unexpected errors causes by these side effects. So far, .NET Core seems better in this respect, but we're still nervous about it given the long bug tails of the past.

Given all this, we think this is better off implemented as an opt-in package, rather than building this in to EF Core.

**Comment by wcrowther** [comment]
@ajcvickers After our discussion, I came up with the following solution to this issue outlined in the StackOverflow entry below.

I do the assembly scanning in my EF Core mapping code, looping through the existing sub-types, invoking the existing "builder.HasDiscriminator().HasValue(type, type.Name);" method. So far this method seems to be working fine but let me know if you see any issues or have concerns.

https://stackoverflow.com/questions/65778874/how-to-automatically-map-tph-derived-classes-in-ef-core

**Comment by ajcvickers** [comment]
@wcrowther Looks reasonable to me.
