### ISSUE TITLE
Транслит

### ISSUE THREAD

**Issue by Morcoth** [dotnet/EntityFramework.Docs#3074]
AddRange, **Упдатеранже, Аттачранже и Ремоверанже**  излишний перевод методов UpdateRange , AttachRange и RemoveRange

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: b2657ddd-3ba6-f839-e6b0-e7e199a0d6e5
* Version Independent ID: c7456e25-0783-e271-bfee-3d1c443b2e90
* Content: [Дополнительные функции Отслеживание изменений — EF Core](https://docs.microsoft.com/ru-ru/ef/core/change-tracking/miscellaneous#addrange-updaterange-attachrange-and-removerange)
* Content Source: [entity-framework/core/change-tracking/miscellaneous.md](https://github.com/dotnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/core/change-tracking/miscellaneous.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Rick-Anderson Why is the translator trying to translated non-English words? UpdateRange **is not an English word**, so any translation of it from English must be an error.

**Comment by JasonCard** [comment]
@ajcvickers This article is machine translated and our MT engine is not able to automatically recognize which words should or should not be localized. So in order to prevent over-localization of non-English words, either `code style` or [no-loc syntax](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings) should be used in the source content.

**Comment by roji** [comment]
Code-fencing as per https://github.com/dotnet/EntityFramework.Docs/issues/3068#issuecomment-774459578
