### ISSUE TITLE
Verify method was called when writing unit tests with inMemory database

### ISSUE THREAD

**Issue by tinuverma** [dotnet/EntityFramework.Docs#3082]
While this works great for a complex unit test I am writing, one thing I see missing is - how can I verify if "SaveChanges" or "SaveChangesAsync" or any other method available on DbContext was called?
In some cases I want to make sure it was called only once.
Is there something I am not seeing - since this is actual context and not moq?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ef36e12-dfc2-ac09-76b7-4af887bc39c1
* Version Independent ID: 87e16518-5ade-2159-ba56-11fbf6b2bf69
* Content: [EF Core testing sample - EF Core](https://docs.microsoft.com/en-us/ef/core/testing/testing-sample)
* Content Source: [entity-framework/core/testing/testing-sample.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/testing/testing-sample.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
@ajcvickers

**Comment by roji** [comment]
@tinuverma you seem to be asking for mock-like verification that SaveChangesAsync was called exactly once. This isn't possible with InMemory, since InMemory is a "fake" (alternate database implementation) rather than a mock; it's useful to read [this article](https://martinfowler.com/articles/mocksArentStubs.html) to understand the differences. As such, InMemory can be used with "state verification" - you can do verification by querying the InMemory database and making sure it has the state it should (e.g. that some entity was properly added). But it's not possible to do "behavior verification", i.e. to know exactly which method invocations were done on it.

Note that it is possible to combine both approaches: you can use the InMemory provider to query fake test data, but also mock your DbContext and verify calls to Add, SaveChangesAsync, etc.

**Comment by ajcvickers** [comment]
@tinuverma You can use the `SavingChanges`\`SavedChanges` event on the context to determine if  `SaveChanges` was called.
