### ISSUE TITLE
TPT without explicit `ToTable` for each derived type?

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/EntityFramework.Docs#3084]
We currently have a base class, `Entity`, for all our entities in its own separate `entity` table

```c#
class Entity { }
class Post : Entity { }
class Blog : Entity { }
```

Is there a way to tell EF core that all classes deriving from `Entity` is TPT without explicitly calling `ToTable`?

```c#
modelBuilder.Entity<Entity>().ToTable("entity"); // this is fine

// we'd like these to be handled implicitly by `UseSnakeCaseNamingConvention`: https://github.com/efcore/EFCore.NamingConventions
modelBuilder.Entity<Post>().ToTable("post");
modelBuilder.Entity<Blog>().ToTable("blog");
```

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a10898c5-abee-1843-cfff-b2707f8a079a
* Version Independent ID: d9399618-488e-20b1-f707-35a191b95cc1
* Content: [Inheritance - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance?source=docs)
* Content Source: [entity-framework/core/modeling/inheritance.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/inheritance.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@gojanpaolo if you don't specify ToTable on the child entities, EF Core assumes that they are mapped to the same table as the parent; in other words, it sets up TPH (a single table for the entire hierarchy). ToTable - with a specific table name - is necessary in order to configure TPT.

One thing you can do, is go over all the entities yourself in OnModelCreating, and call ToTable with a transformed table name:

```c#
var snakeCaseNameRewriter = new SnakeCaseNameRewriter(CultureInfo.InvariantCulture);

foreach (var entityType in modelBuilder.Model.GetEntityTypes())
{
    if (entityType.BaseType is not null)
    {
        entityType.SetTableName(snakeCaseNameRewriter.RewriteName(entityType.GetTableName()));
    }
}
```

Note that this makes it impossible to use TPH, which is why EFCore.NamingConventions cannot do it for you. Note also that SnakeCaseNameRewriter is an internal type, so this code may break in the future and require adjustment (though probably nothing major).

**Comment by AndriySvyryd** [comment]
After https://github.com/dotnet/efcore/issues/214 Is implemented it should be possible to add a custom annotation that will be picked up by a custom convention that sets up the TPT hierarchy.

**Comment by gojanpaolo** [comment]
Got it! Thanks for the responses! We'll iterate over the entities in `OnModelCreating` for now and keep track of dotnet/efcore#214. Thank you!
