### ISSUE TITLE
Exception behavior, structure changes missing

### ISSUE THREAD

**Issue by rarera** [dotnet/EntityFramework.Docs#3155]
Hello, can you please add information about structure and behavior changes going from EF6 to EF Core?
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cbb86f3-378b-e83d-56c3-c0532192bd13
* Version Independent ID: c96b2fcb-8af0-f05b-e188-a6c59dd9f428
* Content: [Porting from EF6 to EF Core - EF](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/)
* Content Source: [entity-framework/efcore-and-ef6/porting/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/efcore-and-ef6/porting/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Differences in areas like this are common since EF Core is a new codebase and has an entirely different internal implementation and provider model. The type of inner exception and how it is structured is also up to the implementing provider, and so isn’t something we could likely document in a general way for EF Core.

You should think of porting from EF6 to EF Core as porting to a new product, not a new version. As such you should expect to test extensively to ensure things like this are caught. (No pun intended.)
