### ISSUE TITLE
HasColumnType 

### ISSUE THREAD

**Issue by smhoff** [dotnet/EntityFramework.Docs#3159]
How about telling us what valid values are for that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cec1a03-d2ee-70e3-5dab-e38d9b32dca2
* Version Independent ID: fb34920f-7e9e-9d39-f5fa-a943b0250fee
* Content: [StringPropertyConfiguration.HasColumnType(String) Method (System.Data.Entity.ModelConfiguration.Configuration)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.modelconfiguration.configuration.stringpropertyconfiguration.hascolumntype?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity.ModelConfiguration.Configuration/StringPropertyConfiguration.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.ModelConfiguration.Configuration/StringPropertyConfiguration.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
