### ISSUE TITLE
Which "entities" are referred to here?

### ISSUE THREAD

**Issue by jberent** [dotnet/EntityFramework.Docs#3162]
[Enter feedback here]
re: "Note that entities that are already in the context in some other state will have their state set to Unchanged."

The use of the plural "entities" and the phrase "repopulate a context" make it sound like some other entity besides the one being attached will be set to the 'unchanged' state. I have not seen that in practice and have been unable to make it occur in testing. Could you clarify under what conditions another entity would be set to `unchanged` when using this method?
Or should it be "Note that **an** entity that **is** already in the context in some other state will have **it's** state set to Unchanged."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c4d50d-a88b-36d7-885a-38bb5ff15fad
* Version Independent ID: 7ffdf124-d6ff-401c-3ecf-037b46f7a7a1
* Content: [DbSet&lt;TEntity&gt;.Attach(TEntity) Method (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dbset-1.attach?view=entity-framework-6.2.0#System_Data_Entity_DbSet_1_Attach__0_)
* Content Source: [EF/xml/System.Data.Entity/DbSet`1.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/DbSet`1.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
