### ISSUE TITLE
EF Core as of .NET 2.1 Distributed Transactions needs clarrification

### ISSUE THREAD

**Issue by rcollette** [dotnet/EntityFramework.Docs#3170]
> As of .NET Core 2.1, the System.Transactions implementation does not include support for distributed transactions,

Does this mean for .NET Core 2.1 and older or for versions 2.1 and newer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@rcollette distributed transactions aren't currently supported by any version of .NET Core - only by .NET Framework. Submitted #3171 to update the text to say 5.0 instead of 2.1.

Note that System.Transactions and TransactionScope can be used for non-distributed transactions as well - that's supported in .NET Core.
