### ISSUE TITLE
nameof preferred to magic string

### ISSUE THREAD

**Issue by DickBaker** [dotnet/EntityFramework.Docs#3177]
for "context.People.Include("School").ToList()" read "context.People.Include(nameof(School)).ToList()"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a3ce6e-43ab-e0af-01b3-a82fdaf3cb31
* Version Independent ID: 320e7305-e0a3-a1c6-77f2-1d3029b660b1
* Content: [Eager Loading of Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager)
* Content Source: [entity-framework/core/querying/related-data/eager.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/related-data/eager.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
We discussed this, but since the code is showing explicitly that a string can be used, we would rather leave it as an explicit string literal. You can, of course, use nameof if you know the property at compile time, but it's more common to use the string overloads when you're dynamically finding the name.
