### ISSUE TITLE
Incorrect link to IDbConnectionInterceptor

### ISSUE THREAD

**Issue by deanis74** [dotnet/EntityFramework.Docs#3213]
The description mentions , and links to, `IDbConnectionInterceptor`. It should be `IDbTransactionInterceptor`. 

The links to `Committing()` and `Committed()` already correctly point to methods under `IDbTransactionInterceptor`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1666c0a8-75ac-562a-7035-b79fd6910be0
* Version Independent ID: cdae8024-0463-bc0e-3290-96ba90e40336
* Content: [DbTransactionDispatcher.Commit(DbTransaction, DbInterceptionContext) Method (System.Data.Entity.Infrastructure.Interception)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.infrastructure.interception.dbtransactiondispatcher.commit?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity.Infrastructure.Interception/DbTransactionDispatcher.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.Infrastructure.Interception/DbTransactionDispatcher.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by deanis74** [comment]
Not sure why this was closed. This is a documentation issue, and nothing in the EF code base. The link here is wrong:

https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.infrastructure.interception.dbtransactiondispatcher.commit?view=entity-framework-6.2.0
