### ISSUE TITLE
EF Core Testing Sample Should be Easier To Use

### ISSUE THREAD

**Issue by richardcox13** [dotnet/EntityFramework.Docs#3249]
A link to a folder in a git repo in the middle of the docs requires extraction from the entire repo, is not immediately runnable on being loaded into VS.

- Include a solution file with all projects included (not clear since not just three sibling folders containing project files)
- A download of a ZIP of the entire solution, or its own repo
- Comments that explain where provider specifics (eg. in `BlogServiceTests.CreateContext` that explain _why_ this is done).

An expectation that someone looking at this sample has used EF Core is reasonable, but not that they already know how to use the testing providers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8a5d45-1ea8-4d4a-e4d6-5a6f0f4a0331
* Version Independent ID: 96de1be9-333b-1d52-e8dc-6bae487b85e6
* Content: [Testing with the EF In-Memory Database - EF Core](https://docs.microsoft.com/en-us/ef/core/testing/in-memory)
* Content Source: [entity-framework/core/testing/in-memory.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/in-memory.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
> Include a solution file with all projects included (not clear since not just three sibling folders containing project files)

We do have [a solution file](https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Samples.sln) referencing all samples projects. The expectation is for users to simply open that and navigate to the project(s) they're interested in.

> A download of a ZIP of the entire solution, or its own repo

This is a standard functionality of Github:

![image](https://user-images.githubusercontent.com/1862641/119185175-c04b4e00-ba76-11eb-9d02-7cb93ac9d4f3.png)

> Comments that explain where provider specifics (eg. in BlogServiceTests.CreateContext that explain why this is done).

We cover basic context configuration in various entry-level doc pages, such as the [first EF Core App page](https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli), or the [DbContext configuration page](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/#simple-dbcontext-initialization-with-new). This knowledge is considered very basic in EF Core and is assumed to be already known here (otherwise we must document absolutely everything in all samples...).
