### ISSUE TITLE
The recommended way to deploy migrations to a production is not good

### ISSUE THREAD

**Issue by barsv** [dotnet/EntityFramework.Docs#3266]
I don't understand the recommendation to use scripts to deploy to production. 
"Experience has shown that the simplicity of this deployment strategy is outweighed by the issues it creates." - it would be nice to elaborate on it. Otherwise it sounds like "do so just because I told so".
Two points in the section "The advantages of this strategy" are contradictory. At first it says "SQL scripts can be reviewed for accuracy" and later it says "SQL scripts ... can even be generated as part of your CI process.". So if the scripts are generated during CI then they are already not reviewed, right?
Reviewing the scripts in general doesn't sound like a good idea to me. Humans are not robots to apply sql scripts in their heads and understand all consequences. Usually we use QA environments to test that the migrations are getting applied correctly.
Also as far as I understand to generate a script I need to know the current last migration in production. It's one more step where a human error can happen. What if I do a mistake and identify the current production migration incorrectly? Or what if I want to prepare the script in advance and I don't know for sure what the migration will be on production on the go-live day? 
What if I have 2 code branches, I prepared the script using `dotnet ef migrations script AddNewTables` today but tomorrow I did a merge. With `db.Database.Migrate();` I'm sure that if migrations were successfully applied to QA environment then they will be applied correctly to the production db. But with sql scripts I don't have this confidence. Also I will have to do the analysis on the go-live day while I might already forget what were the migrations that I created a week ago. Also I can't test the script in QA. What if I update production not once in a week but once in a month? Developers will not remember what was done a month ago. With `db.Database.Migrate();` approach we were able to successfully apply hundreds of migrations to old systems that were running for years without updates.
We update QA after every bug is fixed. To test that the generated script will work fine on go-live day I will have to revert the QA database to the production state, apply the script and retest that QA is working fine. It nullifies the whole idea of having migrations that just work.
"In some cases, the scripts can be tuned to fit the specific needs of a production database." - isn't it better to do such customizations at the time when a migration is created? If I want to do something specific for production db then I can use `if (Environment == "Prod") { ... }` this way I will not forget to do whatever is needed on the go-live day.
From the whole list of "The advantages of this strategy" the only one left is "SQL scripts can be provided to a DBA, and can be managed and archived separately." - it's questionable again. What is the purpose of such archive? Bureaucracy? 
I think that the recommendation to use `dotnet ef migrations script` for production updates is not good.

**Comment by roji** [comment]
>  "Experience has shown that the simplicity of this deployment strategy is outweighed by the issues it creates." - it would be nice to elaborate on it. Otherwise it sounds like "do so just because I told so".

The points after each deployment method explain the pros and cons. This is a summary of that.

> Two points in the section "The advantages of this strategy" are contradictory. At first it says "SQL scripts can be reviewed for accuracy" and later it says "SQL scripts ... can even be generated as part of your CI process.". So if the scripts are generated during CI then they are already not reviewed, right?

Not really - you can (and should) review CI artifacts. Generating the script during CI doesn't mean automatically applying it as part of CI.

>  Reviewing the scripts in general doesn't sound like a good idea to me. Humans are not robots to apply sql scripts in their heads and understand all consequences. Usually we use QA environments to test that the migrations are getting applied correctly.

Reviewing a SQL DDL script that was auto-generated by a tool - which could cause massive damage - before applying it to your production database seems like a good idea to me. Migrations generally aren't supposed to happen all the time, so devoting a bit if time to this seems to make sense.

However, if you trust your automation testing and QA environments enough that you don't feel like you need to review, by all means do that. I wouldn't say that's a good general recommendation though.

> Also as far as I understand to generate a script I need to know the current last migration in production.

Check out idempotent migrations.

> Or what if I want to prepare the script in advance and I don't know for sure what the migration will be on production on the go-live day?

You can't generate a script if a migration hasn't been added yet, since the script is supposed to contain the SQL representation of that migration. Generate your SQL script after your migrations have been added and you know what package of changes you are going to push to Q&A and/or live.

> In some cases, the scripts can be tuned to fit the specific needs of a production database." - isn't it better to do such customizations at the time when a migration is created

This refers to direct changes in the SQL, which cannot always be (easily) done in the C# migration. For example, you may need to add some option to a CREATE TABLE which EF Core simply doesn't generate.

Re the other points... Rather than answering directly, you seem to have a scenario where db.Database.Migrate() works well for you; if you're happy with that, that's great - nobody is telling you to change it. However, there are many types of scenarios and environments in the world, and in our experience helping users out, doing migrations as part of application startup create lots of issues. 

You may have missed the part about multiple application instances starting up - and attempting to apply the migrations concurrently - or maybe you just have one server. Maybe you also don't care about giving elevated permissions to your application, rather than restricting potentially dangerous DDL to a separate account (these points are all listed in the docs). All that is totally fine, and you should do whatever works for you. But as a *general* recommendation, we believe SQL scripts are the way to go.

**Comment by barsv** [comment]
I appreciate very much that you don't ignore feedback.

> This refers to direct changes in the SQL, which cannot always be (easily) done in the C# migration. For example, you may need to add some option to a CREATE TABLE which EF Core simply doesn't generate.

If I need to add something special that EF doesn't generate I can always remove the C# code that creates a table and insert my SQL code directly using Sql("create table ...").

> You may have missed the part about multiple application instances starting up - and attempting to apply the migrations concurrently - or maybe you just have one server.

I haven't missed that part. The concurrency issue can be easily solved. For example, by creating a separate console application that applies migrations as described here: https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-8-running-database-migrations-using-jobs-and-init-containers/
Or if there is a strong desire to run `db.Database.Migrate()` in the web app startup code then it's still possible to do a distributed lock to avoid concurrency issues.

> You can't generate a script if a migration hasn't been added yet, since the script is supposed to contain the SQL representation of that migration. 

Exactly. And it means that I can't prepare the script in advance. I will have to do it on the go-live day or close to it. Because if I generate the script in advance then there is a chance that a hotfix migration will be applied to production and I will have to regenerate the script again. I might have lots of other things to do on the go-live day and I would prefer to not worry about migrations if possible. Especially if the migrations were done a while ago.

> Reviewing a SQL DDL script that was auto-generated by a tool - which could cause massive damage - before applying it to your production database seems like a good idea to me. Migrations generally aren't supposed to happen all the time, so devoting a bit if time to this seems to make sense.

I think that my main point is that it's better to review generated SQL at the point of time when I create the migration, not before applying it to production several days or months later. If we agree on this then the point that "SQL scripts can be reviewed for accuracy;" can be removed from the list of pros for the deployments using scripts vs `db.Database.Migrate()`. Review of the generated SQL can be done without using it for deployment.

> you seem to have a scenario where db.Database.Migrate() works well for you; if you're happy with that, that's great - nobody is telling you to change it.

Yes, and I'm not going to change it. But there is this controversial recommendation. And it's not from a nobody guy, it's from Microsoft who developed EF. It may be a reference point for someone who will come and ask "why you do not follow recommendations from Microsoft who developed EF". The recommendation also maybe misleading for new comers.

**Comment by roji** [comment]
> If I need to add something special that EF doesn't generate I can always remove the C# code that creates a table and insert my SQL code directly using Sql("create table ...").

But then you need to replace the .NET `migrationBuilder.CreateTable(...)` directive with the entire SQL fragment for that. For one thing, where would you even get that fragment from? You generally still want the SQL generated by EF, but you want to be able to tweak it.

> The concurrency issue can be easily solved. For example, by creating a separate console application that applies migrations as described here

That is indeed much better, but we are seeing a large majority of EF users applying migrations at regular app startup, without giving any thought to concurrency etc. This is the thing we really recommend against (and this is why this doc page is worded as it is). If you use Migrate programmatically from a dedicated program and take care to do it without anything running, that's much better.

>  Or if there is a strong desire to run db.Database.Migrate() in the web app startup code then it's still possible to do a distributed lock to avoid concurrency issues.

That is *really* not a trivial thing to do correctly. Also, it's not just preventing *migrations* from happening concurrently - an app instance could be running (not applying migrations), and accessing the database as its schema is being modified.

> Exactly. And it means that I can't prepare the script in advance. I will have to do it on the go-live day or close to it. Because if I generate the script in advance then there is a chance that a hotfix migration will be applied to production and I will have to regenerate the script again. I might have lots of other things to do on the go-live day and I would prefer to not worry about migrations if possible. Especially if the migrations were done a while ago.

The assumption here in general is that between your commits (which add migrations) and go-live there's some time - after all people typically deploy to a test (or Q&A) platform, verify that everything is correct, and only then move to actual go-live. Call this the "golive preparation phase" - that's when you'd be preparing your script and reviewing it. You can think of a SQL migration script review as part of your standard Q&A process, if you want.

> I think that my main point is that it's better to review generated SQL at the point of time when I create the migration, not before applying it to production several days or months later. If we agree on this then the point that "SQL scripts can be reviewed for accuracy;" can be removed from the list of pros for the deployments using scripts vs db.Database.Migrate(). Review of the generated SQL can be done without using it for deployment.

That can really depend on your processes and internal organization. In many organizations, you have a DBA responsible for the database (or devops), which typically are going to want to see the **SQL DDL** you're going to apply, rather than EF C# code which could make changes that aren't immediately observable (your DBA/devops may not even know .NET or EF). It really all depends on your specific scenario.

> But there is this controversial recommendation.

We don't think so. Again, for a go-live, users typically generate the SQL script for the new migrations added since the last go-live (or just use idempotent migrations). At this point, the SQL script makes it extremely clear to everyonewhat's going to happen when the changes are deployed, and any tweaks can be applied as well.
