### ISSUE TITLE
Discuss performance tips around using `Set<T>` and how contexts can be optimised in heavier scenarios

### ISSUE THREAD

**Issue by patrickklaeren** [dotnet/EntityFramework.Docs#3294]
As per [this blog post for EF Core 6 Preview 5](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-5-compiled-models/#dbcontext-instantiation) there is no mention of `Set<T>()` in either the performance or querying section of the docs.

A small remark in the post:

> Performance tip: you can avoid the overhead of DbSet initialization by using an alternate approach such as the context.Set<Entity>() API call.

is the first time I have seen this be mentioned publicly in a wide-reaching post.

This should be expanded upon, or at the very least dumped, into a page on the performance docs, please!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c89e1e66-3c90-23d9-2c92-568e8c57d0ad
* Version Independent ID: 26a9ec30-c290-f9bb-9d65-50d4e785872d
* Content: [Introduction to Performance - EF Core](https://docs.microsoft.com/en-us/ef/core/performance/)
* Content Source: [entity-framework/core/performance/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/performance/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by svengeance** [comment]
I would love to see something along this nature as well. There are obvious higher-level performance tips such as context pooling, no-tracking when needed, etc, but it would be fascinating to read some of the smaller ones that - while not needed for everyday usage - give us insights into how we can get the most out of EF.

**Comment by jeuxjeux20** [comment]
I agree as well, it'd be nice to know whether or not `Set<T>()` should be used, especially with null reference types enabled.

**Comment by JakenVeina** [comment]
Seconding, as I've been using `.Set<T>()` over `DbSet<T>` properties for quite a while now. Some folks tell me I'm nuts, and if so, I'd like to know it.

I can't imagine how it's not a performance boost, though, even if it's rather small. Sure, you're not gonna see much benefit from it, compared to other optimizations, but it's also basically costless. The only pitfall I'm aware of is that EF can miss entity types, if you don't explicitly add them all in `OnModelBuilding()`.

**Comment by roji** [comment]
If you have settable DbSet properties, the DbContext constructor [will use reflection to find them and initialize them with DbSets](https://github.com/dotnet/efcore/blob/main/src/EFCore/Internal/DbSetInitializer.cs#L50). For very perf-sensitive application, this could slow things down when creating new DbContext instances.

However, there are a lot of other things going on when creating new DbContext instances, so perf-sensitive applications should strongly consider using [DbContext pooling](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-constant#dbcontext-pooling). Doing so means the DbContext setup cost (including the setting of DbSet properties) is only paid once per context instance, and from that point the instance is reused.

From a perf perspective, this is better than calling `Set<T>()` every time you execute a query, since doing that adds an additional dictionary lookup to find the set each time. When a DbSet property is used, it has already been set and no lookup is necessary.

So for ideal perf, use DbContext pooling and have DbSet properties. However, it's important that understand that these difference are very likely to be negligible for typical, real-world application where networking and database processing times are likely to dominate.

**Comment by patrickklaeren** [comment]
@roji Would you consider a PR from myself (or anyone who is faster than me) that puts this into the docs, obviously edited/reworded to fit with the style of the docs?

**Comment by roji** [comment]
I generally believe the docs shouldn't be overloaded with details that don't matter to the average EF user (and I think this is a good example). However, a point in the [reducing runtime overhead section](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-constant#reducing-runtime-overhead) could make sense.

**Comment by ajcvickers** [comment]
@patrickklaeren I'd love for you to try different patterns for your particular application and post back the performance differences.

**Comment by roji** [comment]
I agree with @ajcvickers - always good to see concrete numbers with perf. If you show it's significant for a real-world application, it may make sense to highlight this more prominently.
