### ISSUE TITLE
How to access to WebHostBuilder  in Design-time DbContext Creation with top-level statements?

### ISSUE THREAD

**Issue by derigel23** [dotnet/EntityFramework.Docs#3557]
How to access to WebHostBuilder  in Design-time DbContext Creation with top-level statements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 459d20e7-ba25-c162-5721-359ef3562999
* Version Independent ID: d988e806-cb86-19f5-7f76-6ce3bfcd94ed
* Content: [Design-time DbContext Creation - EF Core](https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/cli/dbcontext-creation.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/cli/dbcontext-creation.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@derigel23 I don' think there is a way to do this without refactoring your code to expose a method that returns the WebHostBuilder.

/cc @davidfowl

**Comment by davidfowl** [comment]
Yea that's not supported. If you can show what you were doing before maybe we can help

**Comment by derigel23** [comment]
I was doing these
```
namespace RaidBattlesBot.Model
{
  public class RaidBattlesContextFactory : IDesignTimeDbContextFactory<RaidBattlesContext>
  {
    public RaidBattlesContext CreateDbContext(string[] args)
    {
      var webHostBuilder = Program.CreateWebHostBuilder(args);
      var configuration = webHostBuilder.Build().Services.GetService<IConfiguration>();
      var connectionSting = configuration.GetConnectionString(Startup.ConnectionStringName);

      var optionsBuilder = new DbContextOptionsBuilder<RaidBattlesContext>().EnableSensitiveDataLogging();
      optionsBuilder.UseSqlServer(connectionSting, opts => opts.CommandTimeout((int)TimeSpan.FromMinutes(10).TotalSeconds));

      return new RaidBattlesContext(optionsBuilder.Options);
    }
  }
}
```
I have a complex logic of configuring different configuration sources depending on the environment.
I do not want to repeat it here.

But, as I can see, top-level statements are not for me )

**Comment by davidfowl** [comment]
What you can do is move that logic into a function and share it.

**Comment by powermetal63** [comment]
Several questions regarding usage of EF Core tools with net6 "minimal API" projects have been posted on Stack Overflow (the latest being [C# Entity Framework Core: unable to resolve service](https://stackoverflow.com/questions/71011516/c-sharp-entity-framework-core-unable-to-resolve-service). From the previous responses here apparently it is not supported. But EF Core  documentation topic is not updated, and I think it should. At least, this statement is incorrect now

> Note
>
>When you create a new ASP.NET Core application, this hook is included by default.

since "minimal API" style is default for ne6 projects. It would be nice to explicitly say in the documentation that this style is not supported and eventually provide an example of how it should be refactored (similar to the one currently in [From application services](https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#from-application-services), but with "minimal API" / top-level statements style).
