### ISSUE TITLE
C# 8 NRT links are broken.

### ISSUE THREAD

**Issue by jwooley** [dotnet/EntityFramework.Docs#3618]
The links for the C# 8 Nullable Reference Types in the page https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types are broken. They currently point to https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types but should probably be updated to https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references or https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/nullable-reference-types

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@jwooley I'm not seeing any links to https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types, there's one link at the top to https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types, which does work. Can you point to the broken link?

We could change to point to the NRT spec page (https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) instead of to the tutorial, though I'm not sure that's really better.

**Comment by ajcvickers** [comment]
@roji @jwooley Weird. This link was broken when I tried it yesterday, but is working now.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/1430078/145991395-f5057e70-97fe-4e16-be3b-1fcebce57447.png">

**Comment by roji** [comment]
Weird... some temporary doc system bug?

**Comment by jwooley** [comment]
Confirmed that the link appears t be working again for me now.
