### ISSUE TITLE
Minor point

### ISSUE THREAD

**Issue by dazinator** [dotnet/EntityFramework.Docs#3738]
> Similarly, if an application is accessing the database while another application migrates it, this can cause severe issues.

This point is framed as a point against running migrations from the app and in favour of using another approach, but... this problem applies to all the other approaches as well.. "while another application migrates it" - this could be equally referring to a deployment pipeline, or a terminal running a migration bundle.. 

Just to elaborate... :-)

The key things that helps me decide whether to handle migrations "in app" vs external to the app i.e "in pipeline".

1. Do you need a UX for end users during an upgrade? Easier to do this in app. (New instances come online in "upgrade" mode and show UX)

Caveat: You need to ensure you use a distributed lock when doing it "in app" and multiple instances of app could trigger upgrade.

If you don't need a UX, easier to do it in pipeline as you save yourself the trouble of a distributed lock (and a UX!)

2. Do you need zero downtime deployments?

This doesn't actually make a difference to the approach but does change scope massively.. 
None of the approaches on there own will help you. You need to devise a strategy that allows database upgrades to be applied without breaking running apps. This usually ends up with having to plan schema changes carefully using expand contract pattern for example over multiple releases. Again  it doesn't matter where you choose to apply the changes. 

There is a seemingly definitive point against "in app" and that's the security one. However if you consider that the app generally has read write access to the database - giving it alter permissions as well for schema changes (within same database) is unlikely to make a compromise that much worse in many cases? Also if this is a concern risk can further be diminished by the app upgrade process itself. For example if the app displays a UI where an admin has to login to apply the upgrades then they can enter the required DB credentials to run the migrations under so the app need not store them and the connection is discarded once completed. Maybe this doc assumes the app has to auto apply migrations on startup and has to therefore store credentials to connect with the database with elevated permissions, but that's not the only way of applying upgrades from within the app especially when you introduce a UI for this process within the app.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06b35eff-79e4-2068-6d1c-f9079d43f903
* Version Independent ID: 6c575b10-048c-349c-397e-0d9c11d47235
* Content: [Applying Migrations - EF Core](https://docs.microsoft.com/en-gb/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#bundles)
* Content Source: [entity-framework/core/managing-schemas/migrations/applying.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/applying.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
> This point is framed as a point against running migrations from the app and in favour of using another approach, but... this problem applies to all the other approaches as well.. "while another application migrates it" - this could be equally referring to a deployment pipeline, or a terminal running a migration bundle..

The point is that it's very common for multiple instances of an application to run/start in parallel, but having the same deployment pipelining running at the same time is generally something that should never happen (since the multiple deployments could step on each other). It generally make sense (and easier) to ensure that only one deployment pipeline is running at any given point.

Similarly, running a migration bundle from a terminal is something typically done by a human devops engineer, and it's assumed that organizationally you won't have two people deployment (and therefore running migration bundles) concurrently.

> Do you need zero downtime deployments?

You're right that zero downtime requires additional practices in addition to the above - but that seems orthogonal to the issues with concurrently executing migrations. Whether you're doing zero downtime or not, concurrently executing migrations are something to be avoided.

> However if you consider that the app generally has read write access to the database - giving it alter permissions as well for schema changes (within same database) is unlikely to make a compromise that much worse in many cases?

Table write permissions are quite different from schema modification permissions, and if an application doesn't need to write to a specific table - only read it - then it can be a good idea to restrict that.

> Maybe this doc assumes the app has to auto apply migrations on startup and has to therefore store credentials to connect with the database with elevated permissions, but that's not the only way of applying upgrades from within the app especially when you introduce a UI for this process within the app.

It's true that the warning in this doc targets the (unfortunately) common practice of calling Migrate() on application startup; this is because we see lots of people doing that. I agree that if the application contains a full-blown UI allowing migration execution, things are quite different. However, note if a new version of the application has been deployed, it generally cannot be expected to run properly until the latest migrations are applied as well (since it depends on the latest database schema). Because of this, applying migrations really does seem to be part of deploying and application - to be done at the same time as the program is copied to the production server. In other words, in many cases I'm not sure how valuable it is to deploy an application, and then to require an admin to click on a button in the UI in order to run migrations (as opposed to just run them as part of deployment).

**Comment by dazinator** [comment]
Thank you for the response.

> The point is that it's very common for multiple instances of an application to run/start in parallel, but having the same deployment pipelining running at the same time is generally something that should never happen (since the multiple deployments could step on each other). It generally make sense (and easier) to ensure that only one deployment pipeline is running at any given point.

I agree that "in pipeline" generally removes the need for any distributed locking, and this is something that I have also outlined as a point in its favour (so there is absolutely no argument on that topic) my point wasn't really addressed in that I was specifically commenting on this section from the docs:

> Similarly, if an application is accessing the database while another application migrates it, this can cause severe issues.

Going back to your response above with this in mind, running migrations in a pipeline or even a devops engineer running them manually does not exempt those methods from this exact issue either - they are equally no better. So this point is a general concern no matter the method. Its not really a criticism / point against "in app" and in favour of other methods as it seems to be framed.. The reason being is that If the pipeline or that devops engineer applies migrations whilst apps are still running it will still cause problems. The point here is a general consideration that no matter how you apply migrations if apps are running at the time they will break unless you adopt additional practices to cater for this. There are choices in how you could cater for this. I think there are hidden assumptions in this doc (that are not made clear) that every organisations deployments should or do look like this:

1. Take all apps down
2. Apply migrations
3. bring all new versions up.

I agree if this style of deployment fits with your organisation then the most suitable / least effort model is "in pipeline" but currently the assertions in this doc are not sufficiently qualified imho . I don't agree that this is the only deployment style that makes sense and therefore the "only right way" of doing things is definatley not "in app" as this doc asserts.. I'll try to explain why.

> However, note if a new version of the application has been deployed, it generally cannot be expected to run properly until the latest migrations are applied as well (since it depends on the latest database schema). Because of this, applying migrations really does seem to be part of deploying and application - to be done at the same time as the program is copied to the production server. In other words, in many cases I'm not sure how valuable it is to deploy an application, and then to require an admin to click on a button in the UI in order to run migrations (as opposed to just run them as part of deployment).

I think there is legitimate value to be had with the UI approach so perhaps I can elaborate on that.
I've mentioned deployment style 1 but let me outline the three styles as I see them:

1. Style 1 - Application fully down / offline whilst upgrades applied.
2. Style 2 - Application Degrades - The application / or parts of it, remain accessible throughout the deployment but there is some functional degradation whilst upgrades are being applied, and perhaps some notice to users.
2. Style 3 - Zero Downtime - No functional degradation whilst upgrades are applied.

We've spoken about style 1 and that's the basic model I think this doc has in mind and I agree is probably what many organisations do, especially for internal apps and non mission critical apps.

Let's rule out talking about the mechanics of style 3 suffice to say it is what everyone thinks of typically when they think of Zero Downtime deployments. I will say though it has relevence to the conversation in that, it has tradeoffs with style 2. Organisations pay a price to achieve zero downtime deployments - "there is no free lunch." This brings us on to style 2. If you can accept some functional degradation whilst upgrades are actioned then this is a good compromise between style 1 "going down completely" and style 3 having to pay and enact all the processes necessary for true zero downtime deployments. With style 2, the deployment process looks like this:

1. Deploy new version of the app accross all nodes in cluster (rolling style so no downtime, behind old balancer)
2. The ne
ny functionality that isn't dependent upon the database can remain up. Whether this is worth it depends on the functionality of your application which is why in my view its a decision for the developer to make and a legitimate one. Some examples:-
1. Pages that show content cached from elsewhere or even just static content.
2. Pages that interact with external api's not native or involved with your backend database.


Besides this, the UX is better if when users navigates to the site during an upgrade - rather than a 404 they get to access non degraded parts of the site, and see any helpful UI that the org might want to show to apologies for any inconvenience that the functionality is down whilst site is undergoing maintainence etc.

1. You have a web app deployed behind a load balancer to multiple nodes.
2. Users from around the world can visit it any time.
3. Deployment style 1 would mean the site is completely offline for a window of time that would measurable and negatively impact users and or the business (e.g suppose there is content shown to visitors on parts of the site that is static or from some cache but has value)


So Style 2 is the crux. "Zero downtime - with functional degradation. Scenario: You have a website being used by people all over the world in different timezones, there is no period of time where "no one" i.e no user is not visiting the site. If you take the web application fully down, and it takes 5-10 mins to apply the database upgrade and bring the new site up, you measure this results in a negative impact to some users or perhaps lost opportunities during that window where users turn up and see the site is down and go elsewhere. You can 



theare 2 other styles that may justify different approaches, let's talk about the justification for "in app".

I



when applying migrations and this is not my criticism - i have stated this as a pro in favour of in pipeline vs in app where you would need a lock. So why bother with UI and doing it app then - it seems you dont see any valid reason and thats why you discourage it. Before we move on to why there is a valid justification please lets come back to the poijt However this is not truedistributed locking in the app if you can make it part of a singular deployment pipeline / process. This is what I am trying to outline basically. This issue of running it in a singular pipeline has nothing to do with the actual point I quoted from the doc which was this one:

> Similarly, if an application is accessing the database while another application migrates it, this can cause severe issues.

Having exactly one deployment pipeline running doesn't magically exempt it from this issue. If you have a single pipeline that deploys migrations without bringing all your apps offline first then this exact same issue remains. You don't address this fully - to address this point fully and make it a point against "in app migrations" only, you would need to say that you need to run the migrations in the pipeline and therefore you basically need to take all the apps offline then apply the migrations then bring them online after the migrations have applied. Its at this point that you realise that having a UI and applying from within the app itself means a slightly better user experience.

**Comment by dazinator** [comment]
Sorry - accidentay hit button to "close with comment" half way through editing it! Have just updated it and then re-opened this issue.

**Comment by roji** [comment]
> Going back to your response above with this in mind, running migrations in a pipeline or even a devops engineer running them manually does not exempt those methods from this exact issue either - they are equally no better. So this point is a general concern no matter the method. Its not really a criticism / point against "in app" and in favour of other methods as it seems to be framed..

It is implicitly assumed here, that while deployment is occuring, the application is brought down. It needs to be restarted in any case (since a new version is being deployed), so it seems reasonable for many/most cases to bring it down, deploy the new binaries and apply the migrations, and then bring up the application.

> Style 2 - Application Degrades - The application / or parts of it, remain accessible throughout the deployment but there is some functional degradation whilst upgrades are being applied, and perhaps some notice to users.

In the general case, it seems quite unlikely that an application can still be useful after having been updated, but without the necessary database schema changes being made. That doesn't mean it's impossible to imagine scenarios where this is so, but it certainly seems quite contrived. I also again don't quite see the value of going into all that complexity vs. simply applying the migration as part of deployment, given that we're already accepting some sort of downtime/degraded operation during upgrades.

Stepping back here, the documentation isn't supposed to be a mathematically exhaustive account of all scenarios; application deployment that varies, and obviously each company does their own thing. The main point here is to raise the possible problem points, to make sure that people are aware of them as they make their choice. As I've written, we unfortunately see a lot of people calling Migrate() on startup - simply because it's simple to do - and because they haven't thought things through or aren't aware of the pitfalls. That is the main thing this section targets.

As you've written, there are more advanced/complicated scenarios, e.g. zero-downtime (or possibly the "degraded deployment" model you described above). People who need to do these kinds of things are presumably already aware of what needs to be done, and if someone really wishes to do "degraded deployment", I really doubt they would turn away just because of how our docs our currently worded.

At the end of day, good documentation is always a balance. Too much documentation is intimiating, and makes it very difficult for beginners to understand what's going on. Having said that, if we get more questions/feedback on advanced deployment techniques, we could certainly add a section (or a separate page) dedicated to that; but that hasn't happened until now.

**Comment by dazinator** [comment]
Ok, understood. I am totally on board with that response. I will be very honest in that I do think the doc does not read like this:

> The main point here is to raise the possible problem points, to make sure that people are aware of them as they make their choice

It more reads like: "Do things this way (don't ever apply upgrades "in app") - especially in prod, and we'll state some reasons why - some are general points and some contain our implicit assumptions which are unclear.

If it truly wanted to meet the objective then why  not just state:

1. Don't apply migrations to the database from more than one process / thread at a time. 
  - for this reason we don't recommend applying from app startup as when you have more than one instance running it could be problematic.

Then just leave it at that.
I'll close this issue now - I hope this came accross in a good nature and I appreciate I possibly have stronger opinions than many, apologies for that :-)

**Comment by roji** [comment]
> Do things this way (don't ever apply upgrades "in app")

Can you be more specific on where it reads like that? The closest I can see is [in this section](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#apply-migrations-at-runtime) is "this approach is inappropriate for managing production databases", which certainly doesn't seem as strong as you're making it out to be.

> If it truly wanted to meet the objective then why not just state:

Mostly because there are other reasons listed below (security, rollback management...). The concurrent issue is only one of several points.

> I'll close this issue now - I hope this came accross in a good nature and I appreciate I possibly have stronger opinions than many, apologies for that :-)

No worries at all, always good to discuss this stuff.

**Comment by dazinator** [comment]
> Can you be more specific on where it reads like that? The closest I can see is [in this section](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#apply-migrations-at-runtime) is "this approach is inappropriate for managing production databases", which certainly doesn't seem as strong as you're making it out to be.

You're right, It's not as bad on a second (more objective) reading as I was (mis)remembering. I retract my criticism in this regard with my apologies. I think overall it does just about strike the balance you mentioned. The 'inappropriateness' bit was probably the provoker for me on first read. There are scenarios where you have no choice but to handle applying db upgrades from the app (consider xamarin android app distributed to users through an apk store for instance) - but even there you should still apply pregenerated sql scripts, rather than calling the ef ApplyMigrations method to generate sql on the fly) so when this point is also factored in I think its.. fair.

> No worries at all, always good to discuss this stuff.

Thank you for the professionalism reflective of the EF Core team. Will close this one.

**Comment by roji** [comment]
Thanks, and thanks for engaging!
