### ISSUE TITLE
Possibly add `[MemberNotNull]` attribute as a way of supressing compiler warnings

### ISSUE THREAD

**Issue by mystiquewolf** [dotnet/EntityFramework.Docs#3866]
If it is somehow possible to use the `[MemberNotNull]` attribute to suppress compilers warnings for `Non-nullable property must contain a non-null value when exiting constructor.` errors, it would be good to document this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
[MemberNotNull] is useful when some helper method initializes a non-nullable property, and that helper method is called from a constructor. It allows common initialization code to be factored in a single helper method, called by multiple constructors, instead of having to initialize in the constructor body itself.

So this generally falls under "constructor binding", which is [already documented on this page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#non-nullable-properties-and-initialization). If you're OK with always initializing an NRT property via the constructor, then you should definitely do that: it would make the warnings/errors go away. [MemberNotNull] only helps if you want to extract that initialization to a separate helper method.
