### ISSUE TITLE
Compiled Queries v. Stored Procedures

### ISSUE THREAD

**Issue by xenophilios** [dotnet/EntityFramework.Docs#3908]
Would appreciate some comment on the relative benefits and drawbacks of compiled queries and stored procedures.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e638463f-fec2-ca39-37a4-b3580fa874d8
* Version Independent ID: e96b453f-0256-8bc9-bd21-1343f2fe246c
* Content: [Advanced Performance Topics](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dbcontext-pooling)
* Content Source: [entity-framework/core/performance/advanced-performance-topics.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/performance/advanced-performance-topics.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@xenophilios these are two very different concepts:

* A stored procedure is logic defined in your database and written in a SQL-like procedural language, which can be invoked from the client. That is, you no longer express LINQ which gets translated to SQL queries accessing tables, but instead you call the stored procedure, and the database-encapsulated logic runs.
* Compiled queries are simply an EF Core feature for (slightly) speeding up its internal query processing. EF still translates your LINQ to SQL and sends it to the database as usual; it's purely a client-side EF optimization for high-perf scenarios.

**Comment by xenophilios** [comment]
Thank you for the fast response.
My concern is not so much what these things are, but which is better for speeding up database queries. Can they be used together?

**Comment by roji** [comment]
@xenophilios since with stored procedures EF doesn't send queries, the compiled query feature generally isn't relevant. Neither is "better" than the other, they just do very different things.

I'd generally recommend avoiding stored procedures and let EF directly generate queries in SQL, unless you have specific reasons to do so. These reasons may be that you're constrained to use stored procedures which already exist in your database, or possibly that you need to perform multiple complex operations (queries, updates) and which to avoid multiple roundtrips by wrapping all of these in a single procedure call.

**Comment by xenophilios** [comment]
Thank you for this very helpful information!
