### ISSUE TITLE
Logging to a File with a Data Context Pool

### ISSUE THREAD

**Issue by xenophilios** [dotnet/EntityFramework.Docs#3909]
Would appreciate some guidance on how to set up logging to a file, and specifically on how to dispose of the stream, when using a data context pool, since with a data context pool, OnConfiguring() cannot be overridden. Am assuming use of AddDbContextPool in ConfigureServices in Startup.cs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2643b9b-117a-8cd8-6b26-8a7ebf43cd78
* Version Independent ID: ab4359e9-9fc2-437a-d586-f580d6e7c4f9
* Content: [Simple logging - EF Core](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging)
* Content Source: [entity-framework/core/logging-events-diagnostics/simple-logging.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/logging-events-diagnostics/simple-logging.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
> Am assuming use of AddDbContextPool in ConfigureServices in Startup.cs.

This suggests you are using Dependency Injection, possibly in an ASP.NET Core application. If that's the case, consider using [Microsoft.Extensions.Logging](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/extensions-logging?tabs=v3) - which is what ASP.NET also uses - rather than simple logging (which is specific to EF Core). This way you have one logging configuration for your entire application.

As to how to log to a file with Microsoft.Extensions.Logging, there are many tutorials out there. For example, it's common to use [Serilog](https://serilog.net) and configure that to log to a file.

**Comment by roji** [comment]
Closing as the question seems to be answered, but don't hesitate to post back if you have further questions.
