### ISSUE TITLE
Broken relationships due to ChangeTracker being cleared before the assertions

### ISSUE THREAD

**Issue by Wokarol** [dotnet/EntityFramework.Docs#3920]
The whole article was really good, and worked wonderfully except for a the code example. Mainly the following line:

```cs
    context.ChangeTracker.Clear();

    var blog = context.Blogs.Single(b => b.Name == "Blog3");
    Assert.Equal("http://blog3.com", blog.Url);
```

Should the Change Tracker be cleared **before** the assertion is checked?
In my case if I do it like that, the following code **passes**:
```cs
    ctx.Foos.Should().HaveCount(1);
    timestamp.Foo.Should().Be(await ctx.Foos.FirstAsync());
```
While this code fails:
```cs
    // ctx.Foos.Should().HaveCount(1);
    timestamp.Foo.Should().Be(await ctx.Foos.FirstAsync());
```

If I put the clear after, the issue is not present. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7fc3c3b-c859-2ad5-78f3-ce57d3c9bc2d
* Version Independent ID: b7fc3c3b-c859-2ad5-78f3-ce57d3c9bc2d
* Content: [Testing against your Production Database System - EF Core](https://docs.microsoft.com/en-us/ef/core/testing/testing-with-the-database)
* Content Source: [entity-framework/core/testing/testing-with-the-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/testing-with-the-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Wokarol Yes, the `Clear` call is intended. As it says in the text,

> After making the updates we want, we clear the context instance's change tracker with [ChangeTracker.Clear](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetracking.changetracker.clear), to make sure we actually load the blog from the database below. We could use two context instances instead, but we'd then have to make sure the same transaction is used by both instances.

**Comment by Wokarol** [comment]
@ajcvickers, that's not what I meant. 
The issue is not with the clear being there, but with it being before the assertion calls.

**Comment by ajcvickers** [comment]
@Wokarol The code in the doc is as intended. The change tracker is cleared after SaveChanges to ensures that a new entity is created and tracked by the query. If the change tracker is not cleared, then the data in the database will not be used because the context is already tracking the entity, and so it will be returned instead.

I'm not sure what you are trying to assert with the timestamp; that's not in the document referenced. If you post the full code of your entity and tests, then I can take a look at what is going on.

**Comment by Wokarol** [comment]
Sure, there is a bit too much code to post tho. But tomorrow I will try making an small example which has the same issue.

**Comment by Wokarol** [comment]
Okay, sorry for the delay @ajcvickers, here is the isolated example. I have Database Context defined as so:
```cs
public class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions options) : base(options)
    {
    }

    public DbSet<Timestamp> Timestamps { get; set; } = null!;
    public DbSet<DataRecord> Records { get; set; } = null!;
}

public class Timestamp
{
    public int Id { get; set; }

    public virtual DataRecord? Record { get; set; }
}

public class DataRecord
{
    [Key] public int TimestampId { get; set; }
    public virtual Timestamp Timestamp { get; set; } = null!;

    public int SomeData { get; set; }
}
```
Simple basic DbContext with one-or-zero-to-one relationship

Then when testing I use this code:
```cs
[Fact]
public void ClearBefore_DontCheckCount()
{
    ApplicationDbContext ctx = CommonInstructions();

    ctx.ChangeTracker.Clear();

    var t = ctx.Timestamps.FirstAsync().Result;

    t.Record.Should().Be(ctx.Records.FirstAsync().Result);
}

[Fact]
public void ClearBefore_CheckCount()
{
    ApplicationDbContext ctx = CommonInstructions();

    ctx.ChangeTracker.Clear();

    ctx.Records.Should().HaveCount(1);

    var t = ctx.Timestamps.FirstAsync().Result;
    t.Record.Should().Be(ctx.Records.FirstAsync().Result);
}

[Fact]
public void ClearAfter_DontCheckCount()
{
    ApplicationDbContext ctx = CommonInstructions();

    var t = ctx.Timestamps.FirstAsync().Result;

    t.Record.Should().Be(ctx.Records.FirstAsync().Result);

    ctx.ChangeTracker.Clear();
}

[Fact]
public void ClearAfter_CheckCount()
{
    ApplicationDbContext ctx = CommonInstructions();

    ctx.Records.Should().HaveCount(1);

    var t = ctx.Timestamps.FirstAsync().Result;
    t.Record.Should().Be(ctx.Records.FirstAsync().Result);

    ctx.ChangeTracker.Clear();
}

private ApplicationDbContext CommonInstructions()
{
    var ctx = Fixture.CreateContext();
    ctx.Database.BeginTransaction();

    Timestamp timestamp = new()
    {
    };

    DataRecord record = new()
    {
        Timestamp = timestamp,
        SomeData = 5,
    };

    ctx.Timestamps.Add(timestamp);
    ctx.Records.Add(record);
    ctx.SaveChanges();

    return ctx;
}
```
using the Fixture from the article

All 4 tests perform the same logic but differ in two aspects:
1. When the tracker is cleared
2. Is the count on Record DbSet checked

So logically all 4 tests should pass (as the logic is the same)

Yet, when running the tests that's proven to not be true
![image](https://user-images.githubusercontent.com/38141841/178729614-483d16d4-e364-480a-8061-57480728b4fa.png)

Which leads to a "quantum" situation where observing the table changes its content.

You get what I mean by that?

Here is the whole sample project if you need it
[EntityFrameworkSample.zip](https://github.com/dotnet/EntityFramework.Docs/files/9101896/EntityFrameworkSample.zip)

**Comment by smitpatel** [comment]
Missing "Include"

**Comment by ajcvickers** [comment]
@Wokarol Calling `CommonInstructions` results in a context that is tracking the two entities that were saved to the database:

```
DataRecord {TimestampId: 1} Unchanged
  TimestampId: 1 PK FK
  SomeData: 5
  Timestamp: {Id: 1}
Timestamp {Id: 1} Unchanged
  Id: 1 PK
  Record: {TimestampId: 1}
```

This means that when a query is made for the `Timestamp` with `ctx.Timestamps.FirstAsync()`, the result is the `Timestamp` entity that is already tracked, and is referenced by and to the `DataRecord` entity. Likewise, when a query is made for the `DataRecord` with `ctx.Records.FirstAsync()`, the result is the `Timestamp` entity that is already tracked, and is referenced by and to the `Timestamp` entity.

After calling `ctx.ChangeTracker.Clear()`, these entities are no longer tracked. This means that after a query for `ctx.Timestamps.FirstAsync()`, only the single `Timestamp` is tracked and it is not fixed up to any `DataRecord`, and vice-versa. If you want both entities to be tracked after the query, then you'll need to use an `Include`. For example, `ctx.Timestamps.Include(e => e.Record).FirstAsync()` or `ctx.Records.Include(e => e.Timestamp).FirstAsync()`.

More generally, the point being made in the document is that after the entities are saved (i.e. in your `CommonInstructions`), then the change tracker should be cleared so that the tests are then starting with a "clean" context instance, rather than one that is still tracking the entities used in the test setup.

**Comment by ajcvickers** [comment]
@Wokarol A real-life scenario would likely not use the same context instance to do what is done here in `CommonInstructions`. If the record should not be null in the test or real-life, then it needs to be queried with `Include`.

**Comment by Wokarol** [comment]
@ajcvickers // Oh, then my bad. I was mistaked when it comes to how EF works.
I was sure that the Record in Timestamp would be filled in real life scenario without need for include.
Good to know and sorry for the confusion on my part.
