### ISSUE TITLE
Unclear on "No foreign key property" section on shadow foreign key explanation

### ISSUE THREAD

**Issue by dtabaka** [dotnet/EntityFramework.Docs#4070]
In the mentioned section it states "If no foreign key property is found, _a shadow foreign key property_ (https://learn.microsoft.com/en-us/ef/core/modeling/shadow-properties) will be introduced"

Just below that in the same section it says "If a property with the same name already exists, then the shadow property name will be suffixed with a number."  To me, this is confusing.   Why would it even attempt to create one if same name already exists since earlier it states (and in the link above) it will create one if a foreign key property is not found.   

Or does this mean it's created anyway behind the scenes and if one is found with same name it just appends a number?

**Comment by ajcvickers** [comment]
@dtabaka A valid foreign key property must be compatible with the associated primary key. Most importantly, they must have the same type. So a property can have the name that would be used by convention for a foreign key property, but cannot itself be the foreign key property because, for example, it has the wrong type.
