### ISSUE TITLE
Tests which explicitly manage transactions running in paralell

### ISSUE THREAD

**Issue by cosminstirbu** [dotnet/EntityFramework.Docs#4147]
Hello,

In the [Tests which explicitly manage transactions](https://learn.microsoft.com/en-us/ef/core/testing/testing-with-the-database#tests-which-explicitly-manage-transactions) section it is recommended to run the tests sequentially (so not in parallel).

How about using a unique database per test instead, for instance:

```
using System;
using System.Linq;
using System.Threading.Tasks;
using EF.Testing.BloggingWebApi.Controllers;
using EF.Testing.BusinessLogic;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace EF.Testing.IntegrationTests;

public class BaseParalellTransactionalBloggingControllerTest : IAsyncLifetime
{
    public Guid TestGuid { get; } = Guid.NewGuid();

    public string ConnectionString() => $"Server=(localdb)\\mssqllocaldb;Database={TestGuid};Trusted_Connection=True";

    public BloggingContext CreateContext()
        => new BloggingContext(
            new DbContextOptionsBuilder<BloggingContext>()
                .UseSqlServer(ConnectionString())
                .Options);

    public async Task InitializeAsync()
    {
        using var context = CreateContext();

        await context.Database.EnsureDeletedAsync();
        await context.Database.EnsureCreatedAsync();

        context.AddRange(
            new Blog { Name = "Blog1", Url = "http://blog1.com" },
            new Blog { Name = "Blog2", Url = "http://blog2.com" });

        await context.SaveChangesAsync();
    }

    public async Task DisposeAsync()
    {
        using var context = CreateContext();

        await context.Database.EnsureDeletedAsync();
    }

    public void UpdateBlogUrl()
    {
        using (var context = CreateContext())
        {
            var controller = new BloggingController(context);
            controller.UpdateBlogUrl("Blog2", "http://blog2_updated.com");
        }

        using (var context = CreateContext())
        {
            var blog = context.Blogs.Single(b => b.Name == "Blog2");
            Assert.Equal("http://blog2_updated.com", blog.Url);
        }
    }
}

public class ParalellTransactionalBloggingControllerTest1 : BaseParalellTransactionalBloggingControllerTest
{
    [Fact]
    public void UpdateBlogUrlTest() => UpdateBlogUrl();
}

public class ParalellTransactionalBloggingControllerTest2 : BaseParalellTransactionalBloggingControllerTest
{
    [Fact]
    public void UpdateBlogUrlTest() => UpdateBlogUrl();
}

public class ParalellTransactionalBloggingControllerTest3 : BaseParalellTransactionalBloggingControllerTest
{
    [Fact]
    public void UpdateBlogUrlTest() => UpdateBlogUrl();
}

public class ParalellTransactionalBloggingControllerTest4 : BaseParalellTransactionalBloggingControllerTest
{
    [Fact]
    public void UpdateBlogUrlTest() => UpdateBlogUrl();
}

public class ParalellTransactionalBloggingControllerTest5 : BaseParalellTransactionalBloggingControllerTest
{
    [Fact]
    public void UpdateBlogUrlTest() => UpdateBlogUrl();
}

public class ParalellTransactionalBloggingControllerTest6 : BaseParalellTransactionalBloggingControllerTest
{
    [Fact]
    public void UpdateBlogUrlTest() => UpdateBlogUrl();
}
```

I have used different classes `ParalellTransactionalBloggingControllerTest1`, `ParalellTransactionalBloggingControllerTest2`, etc because xUnit doesn't run in parallel the tests from the same class.
 
I did toy around with this in the [TestingWithTheDatabase](https://github.com/dotnet/EntityFramework.Docs/tree/main/samples/core/Testing/TestingWithTheDatabase) project and it works just fine.

Do you have any concerns related to this approach?

And one more thing - there are a few blogposts (https://vladmihalcea.com/how-to-run-integration-tests-at-warp-speed-with-docker-and-tmpfs/ and https://www.fusonic.net/de/blog/fast-unit-tests-with-databases-part-1) recommending using `tmpfs` to mount the data folder of your Docker container in memory, to make your tests even faster, especially when run in CI.

I haven't explored this myself, but if this is applicable to SQL Server as well then maybe it's worth also including this in the docs.

Thank you,
Cosmin

**Comment by roji** [comment]
It's certainly possible to use a database-per-test approach to make these tests run in parallel, but database creation is typically is pretty expensive thing; in other words, if you just naively create/drop a database for each test, chances are that your tests will run (considerably) slower in parallel than you would when sharing the same database in serial.

Of course, you can set up a small number of databases and hand them out to tests, ensuring that each database is used only by one test at a time - that would be an most optimized approach. But that requires more testing infrastructure which may not be worth it... Remember, this is typically necessary only for tests which explicitly manage transactions (e.g. other tests can simply use transactions to roll back at the end of the test, which is much simpler).

> And one more thing - there are a few blogposts (https://vladmihalcea.com/how-to-run-integration-tests-at-warp-speed-with-docker-and-tmpfs/ and https://www.fusonic.net/de/blog/fast-unit-tests-with-databases-part-1) recommending using tmpfs to mount the data folder of your Docker container in memory, to make your tests even faster, especially when run in CI.

Sure. How to manage tests is an extremely open question, and there's a huge number of approaches. We can't really cover everything, and there's a balance to be struck, since piling on too much info would make for information overload and unreadable docs.

**Comment by roji** [comment]
Thanks for the kind words, and I'm always happy to have these conversations. Since I think that tests with explicit transaction management are relatively rare, I'm not sure it's worth adding the above conversation to those docs - but if we see more user interest in these questions, we should definitely consider it.
