### ISSUE TITLE
Specifically document what happens if CancellationToken is cancelled during SaveChangesAsync

### ISSUE THREAD

**Issue by ChrisGroupScape** [dotnet/EntityFramework.Docs#4214]
The page should specifically note what happens if the cancellation token is cancelled DURING the SaveChangesAsync operation.   Are the actions that SaveChangesAsync is writing to the database rolled back, completed or canceled partially?   There are "assumptions" made on other internet sites (stack overflow, reddit) that presume the entire SaveChangesAsync operation is rolled back but I can't quickly confirm it in MS documents. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aece550f-d934-0dae-c3ac-0d9b3660bd1a
* Version Independent ID: aebedd48-a65c-c92e-ab4f-f7b4fe467e03
* Content: [DbContext.SaveChangesAsync Method (Microsoft.EntityFrameworkCore)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.savechangesasync?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@ChrisGroupScape it's fairly universal that triggering a cancellation token cancels the entire operation represented by the method to which it was passed; in other words, no changes would be committed if the cancellation takes effect.

However, since cancellation is a concurrent operation, it's inherently prone to race conditions, and there's no guarantee that the cancellation will be applied before the operation is committed.
