### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by geetmenon** [dotnet/EntityFramework.Docs#4344]
This article does not use a good example to articulate how SplitQuery helps in resolving the cartesian explosion problem.
 - In the problem statement example without SplitQuery, it makes use of 3 tables which results in a cartesian explosion 
 - In the solution statement example with SplitQuery, it makes use of 2 tables,  merely states that it splits it into 2 queries. 

a) First it is not doing an apple to apples comparison between the problem example and the solution example
b) It does not clearly explain how it is resolving the cartesian explosion problem.  It merely states that it splits it into 2 queries. 

It would be helpful,
i ) if it can use the same linq query for both the problem and the solution  (the problem query without using SplitQuery and the solution example using SplitQuery)
ii) if it can clearly mention the numbers of queries it will get split into when using 3 tables (would it result 2 queries or would it result in 3 queries) and why? 
iii) clarify as to what will be the total number of rows returned (for the 3 table query scenario) with the SplitQuery
iv) clarify if the relationship between the 3 tables - Blogs to Posts and Blogs to Contributors (one to many, or many to many or many to one) have an impact on the number of queries it will get split into
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43baa9f3-c415-c328-6c10-53aabaaec652
* Version Independent ID: 4e789a1b-aa88-d194-dc2e-0a23251250d7
* Content: [Single vs. Split Queries - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/single-split-queries)
* Content Source: [entity-framework/core/querying/single-split-queries.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/single-split-queries.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
> In the problem statement example without SplitQuery, it makes use of 3 tables which results in a cartesian explosion
> In the solution statement example with SplitQuery, it makes use of 2 tables, merely states that it splits it into 2 queries.

This documentation page discusses two separate problems caused by joins: cartesian explosion (which requires at least 3 tables in order to occur), and data duplication (which requires only 2). The solution - which is split queries - addresses both these performance issues.

Now, we could duplicate the split query ("solution") part to have one section specifically for cartesian explosion (showing its query) and another specifically for data duplication. However, those two sections would be duplicates of one another for everything but the specific query they show. So we opted to just discuss the solution once, makng the documentation terser, rather than making it longer by repeating the same content twice.

Re-reading this page, it doesn't seem to me to be unclear - the problems are clearly described above, and split query is clearly described as the solution to both. We also haven't received any feedback on this being confusing.

**Comment by geetmenon** [comment]
The is a totally irresponsible response and absolutely unacceptable. The Split Queries section says

 "To work around the performance issues described above, EF allows you to specify that a given LINQ query should be split into multiple SQL queries. Instead of JOINs, split queries generate an additional SQL query for each included collection navigation".

By "performance issues described above", it is clearly referring to cartesian explosion and data duplication problems. So it
s a common solution section for both the problems. But it does not explain how it is fixing the cartesian explosion problem by using split queries (also the problem section linq and the solution section. 

Again and again it is poor documentation. If you do not acknowledge the issue, you will never improve. First please learn to acknowledge the problem please. Your objective should be to make it easier for developers to understand and use it. 

@SatyaNadella, please take note of responses like the above from @roji and take appropriate action to improve your documenation.

**Comment by ajcvickers** [comment]
Note from triage: we reviewed this page and believe the contents is clear and understandable.
