### ISSUE TITLE
Documentation for older versions

### ISSUE THREAD

**Issue by HHHackGit** [dotnet/EntityFramework.Docs#4347]
The .net documentation used to have a choice of .net version and documentation for that version, but that choice is not available now.  How i can read about .net core 3.1 in .net 7 documentation? They are different.

**Comment by roji** [comment]
I assume you're asking about Entity Framework Core documentation - .NET documentation isn't managed in this repo.

With the EF Core conceptual docs, we made the decision to call out specific places where things are different across versions, rather than duplicating the entire documentation. For the [API reference](https://learn.microsoft.com/en-us/dotnet/api/?view=efcore-7.0&preserve-view=true) you can select which version of EF Core you want to see.

**Comment by HHHackGit** [comment]
> Я предполагаю, что вы спрашиваете о документации Entity Framework Core — документация .NET не управляется в этом репо.
> 
> В концептуальных документах EF Core мы решили выделить определенные места, в которых вещи различаются в разных версиях, а не дублировать всю документацию. Для [справки по API](https://learn.microsoft.com/en-us/dotnet/api/?view=efcore-7.0&preserve-view=true) вы можете выбрать, какую версию EF Core вы хотите просмотреть.

Yes. I tried find documentaion about older version of EF and i remember that there was a choice of version, but now he is gone. It's sad because it used to be better.
