### ISSUE TITLE
EF Core extension methods - no good examples here

### ISSUE THREAD

**Issue by davidbarrowsatasos** [dotnet/EntityFramework.Docs#4433]
It would be nice if this page had examples for the "RelationalDatabaseFacadeExtensions" e.g. 

var userIdParm = new SqlParameter("userId", SqlDbType.NVarChar, 450)
{
	Value = userId
};

var platformLeads = await _context.Database
	.SqlQueryRaw<UserDto>("EXECUTE [dbo].[GetPlatformLeadForSpecifiedUser] @userId", userIdParm)
	.ToListAsync();

a) is this syntax safe from SQL injections?  I think so, because when I use "ToQueryString( )" and look at the generated T-SQL, it looks okay - however I wonder if it could still theoretically be an injection attack - the "userId" here is a string which is supposed to be a GUID - and to ensure that, I double-check by doing Guid.TryParse above this; but anyway the point is, whilst you document methods like "FromSql" and "FromSqlRaw", you don't document the ".SqlQuery" and ".SqlQueryRaw" database facade extensions.

b) the page doesn't very clearly explain the difference between "FromSql" (.SqlQuery<T>) and "FromSqlRaw" (.SqlQueryRaw<T>)

thank you for your consideration, -Dave Barrows

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98b01ef5-24a5-5f59-30c9-af264f739815
* Version Independent ID: 98b01ef5-24a5-5f59-30c9-af264f739815
* Content: [SQL Queries - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries)
* Content Source: [entity-framework/core/querying/sql-queries.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/sql-queries.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@davidbarrowsatasos parameter safety in the face of SQL injection attacks and the differences between FromSql and FromSqlRaw are discussed pretty extensively on that page, have you maybe missed [this section](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries#dynamic-sql-and-parameters)?

**Comment by davidbarrowsatasos** [comment]
@roji thanks for that, and I take your point; I didn't read that section carefully enough and it does answer the question about the difference between the two (that's the "b" part of my question).  However GitHub seems to have stripped out part of my code example - I am trying to use the generics which exist in "RelationalDatabaseFacadeExtensions" - and it stripped out the use of the angle brackets.  These generics are seemingly a variation on "FromSql" and "FromSqlRaw" which allow you to map to a specific C# type as the return value.  What I wrote, but which seemed to have been stripped out of my post, was (and I don't know if this will work either but I'll try to use the ampersands):   .FromSqlRaw&lt;UserDto&gt;("EXECUTE [dbo].[GetPlatformLeadForSpecifiedUser] @userid", userIdParm) and the "a" part of my question is, is this use of generics, and the parameter I'm using, safe from SQL injection attacks.  I'm not using string interpolation - I'm using parameters.

**Comment by roji** [comment]
@davidbarrowsatasos when pasting code, either surround it with single-quotes (e.g. `FromSqlRaw<UserDto>` or for a multiline code snippet, use [code fences](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (with syntax highlighting).

Regarding your question, the same section specifically discusses FromSqlRaw which you seem to be asking about, and specifically addresses the safety of using placeholders in the SQL (`@userid`), so it should all be covered there, no?

Bottom line, you should **always** prefer the FromSql method, as it offers a safe-by-default API; there's a specific example under [Passing parameters](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries#passing-parameters) which shows invoking stoerd procedures.

FromSqlRaw should generally only be used if FromSql cannot work, specifically because the database doesn't support parameterization of that part of the SQL (typically column/table/store procedure names).

**Comment by davidbarrowsatasos** [comment]
I appreciate your responses and thank you.  I guess I'm not making myself entirely clear.  There appears to be a difference in behaviour between the extension methods which operate on the "DatabaseFacade", that is, those which are "RelationalDatabaseFacadeExtensions", that operate on _context.Database, in my example, versus these other methods which operate on the context like "context.Blogs" (in the examples shown on the page).  For instance, if you issue a command like this:  'var platformLeads = await _context.Database
                .SqlQueryRaw<UserDto>("EXECUTE [dbo].[GetPlatformLeadForSpecifiedUser] @userId", userIdParm)
                .ToListAsync();' , the command is accepted, and compiles, and, although it uses "SqlQueryRaw", appears to be properly parameterized when viewing the code that EF generates.  However if you try to replace that command with "SqlQuery" (which I believe is the equivalent of "FromSql", it does not compile - there is no overload that accepts 2 parameters in that case.  The point I am trying to make about the documentation is that there are no examples using the "RelationalDatabaseFacadeExtensions".  Only examples which use the "FromSqlRaw" or "FromSql", which are extension methods which operate on the "DbSet", not the "DatabaseFacade".  When you are trying to call a stored proc, you don't care (at least I don't) about operating on the DbSet, because the stored proc is not specific to the DbSet.  These database facade extension methods, as I understand it, only came in one of the most recent version of EF Core.

' // there are no examples using these extension methods, which operate on the "DatabaseFacade".
            var platformLeads = await _context.Database
                .SqlQuery<UserDto>("EXECUTE [dbo].[GetPlatformLeadForSpecifiedUser] @userId", userIdParm)
                .ToListAsync();

            // there are only examples using these extension methods, which operate on the "DbSet".
            var platformLeads2 = await _context.Users.FromSqlRaw("EXECUTE [dbo].[GetPlatformLeadForSpecifiedUser]", userIdParm)
                .ToListAsync();'

**Comment by roji** [comment]
> The point I am trying to make about the documentation is that there are no examples using the "RelationalDatabaseFacadeExtensions".

Those methods are documented under [this section](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries#querying-scalar-non-entity-types) of the same page. It's true that there are no examples showing parameter usage, but they behave identically as the ones shown above.

Basically if you're using the non-raw versions (FromSql, SqlQuery) - which is what you should be doing by default - you integrate parameters via string interpolation as the examples show:

```c#
var blogs = context.Blogs
    .FromSql($"EXECUTE dbo.GetMostPopularBlogsForUser {user}")
    .ToList();
```

Since these methods accept a FormattedString and not a regular string, `user` is sent as a DbParameter and everything is safe.

The raw overloads, in contrast, accept a string; this means that using string interpolation (with curly braces) directly inserts the value into SQL, making the query vulnerable to SQL injection. However, if instead you use a placeholder (`@columnValue`), you can supply the value as an additional parameter to the method, and that becomes a safe DbParameter again.

Hopefully that makes things clearer. Bottom line - as I wrote above - always use the non-raw overloads unless you have a good reason to do something else.

**Comment by ajcvickers** [comment]
There are some more examples here: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#raw-sql-queries-for-unmapped-types

**Comment by davidbarrowsatasos** [comment]
okay thanks very much @roji  and @ajcvickers for this info, it does make things a bit clearer.  I'll close this issue.  Best regards
