### ISSUE TITLE
Linked example page doesn't show any examples

### ISSUE THREAD

**Issue by InteXX** [dotnet/EntityFramework.Docs#4509]
Contrary to the claim, the article linked to in the [Remarks section](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.indentedstringbuilder?view=efcore-7.0#remarks) doesn't contain any usage examples for IndentedStringBuilder.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73ab18e3-2d97-eec3-3809-8db14b638bd2
* Version Independent ID: 1c2ee81c-4481-3b72-8205-f687ca41560b
* Content: [IndentedStringBuilder Class (Microsoft.EntityFrameworkCore.Infrastructure)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.indentedstringbuilder?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/IndentedStringBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/IndentedStringBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@InteXX the Remarks section links to the general section in the EF docs that's related to the API, this doesn't guarantee we've written examples specifically for this API.

IndentedStringBuilder is an API to be used by database providers in order to e.g. generate SQL; it's not intended for use by end users. The number of such APIs exposed by EF is huge, and there's no way we can exhaustively document and provide samples for them all (nor would that be useful).

**Comment by InteXX** [comment]
Very well; thank you for your quick reply.
