### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DeBaFig** [dotnet/EntityFramework.Docs#4596]
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

I would like more information about grouping efficiency is the first one better then the second? I found [this article](https://canro91.github.io/2022/03/07/OptimizeGroupBySQLServer/#:~:text=To%20improve%20queries%20with%20GROUP%20BY%2C%20group%20inside%20a%20common,tables%20to%20find%20other%20columns.) and I believe the second could be better.

**Group by new object**
```cs
 var test =  (from i in tableA
              group i by new { i.column1, i.column2, i.column3 } into g
              select new ViewModelTableA
              {
                 One = g.Key.column1,
                 Two= g.Key.column2,
                 Three= g.Key.column3,
                 Itens = (from m in g
                               m.ID
                              ).ToList()
              }).ToList()
```

**Group by a column and then get columns**
```cs
var test =  (from i in tableA
            group i by i.column1 into g
            let first = g.FirstOrDefault()
            select new ViewModelTableA
            {
               One = first.column1,
               Two= first.column2,
               Three= first.column3,
               Itens = (from m in g
                             m.ID
                            ).ToList()
            }).ToList()
```

**Comment by roji** [comment]
@DeBaFig it's always best to simply set up a quick benchmark and measure the results; this is very easy to do with [BenchmarkDotNet](https://benchmarkdotnet.org) - literally a matter of writing the two methods you want to benchmark.

Otherwise, you can also examine the SQL produced from EF's LINQ queries - logging allows access to that. Which SQL runs faster is sometimes easy (e.g. less operations/shorter SQL frequently means faster performance), but in some cases examining the query plan for a SQL query is a good idea. [See our docs](https://learn.microsoft.com/en-us/ef/core/performance/performance-diagnosis?tabs=simple-logging%2Cload-entities) for more info on this.

**Comment by roji** [comment]
As a side note, your two queries don't appear to be equivalent - the 2nd query does FirstOfDefault whereas the first does not.
