### ISSUE TITLE
Create samples for databinding using EF Core in WPF and WinForms

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/EntityFramework.Docs#778]
Moved from https://github.com/aspnet/EntityFrameworkCore/issues/12396 posted by @Int32Overflow

I am facing the task of implementing a large database application in WPF. I have already worked with small WPF database applications.
Unfortunately, I haven't found an example of large WPF EFC applications.

 **A brief summary of my task:**
- WPF application with MVVM
- Data with Entity Framework Core 2.1 
- IoC container with Repository pattern
- Data editors for master data. Simultaneous processing of data in split screens => No global DbContext possible
  - Add data
  - Edit data
     - Save changes
     - Discard changes
  - Delete data

## Example MockUp of an data editor

![grafik](https://user-images.githubusercontent.com/20139038/41546981-539f4d98-731f-11e8-829d-9a6e658a611f.png)

I start editing "Item 1", then I edit "Item 2" and save "Item 2". I now discard the changes of "Item 1".

How would you design this application?

**Comment by FSharpCSharp** [comment]
Maybe another idea before this example is implemented. How about if the user still had the possibility to create or select the database in the program. This would require even more dynamism and is in the "real" world mostly the order of the day. From my point of view that would make the example really round. Because I haven't seen a real-world scenario where the database is hard-coded in any *.config files or anchored in the program code. Normally everything should be dynamic.

**Comment by ajcvickers** [comment]
Update these guides following 7.0work.
