### ISSUE TITLE
Document high-level model building concepts

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/EntityFramework.Docs#779]
Such as:
* Fluent over Attribute over Convention precedence for mapping
* Last-one-wins in Code First

**Comment by AndriySvyryd** [comment]
Also show how to print out the Debug view of the model before and after model validation.

**Comment by AndriySvyryd** [comment]
### Why should we use conventions instead of hardcoding the configuration in builders
#### Pros

- Composability. The logic contained in a convention doesn't directly depend on logic in other conventions. This makes them easier to test and resilient to code churn.
- Extensibility. Conventions can be added, removed, replaced and reordered by providers and (soon) by users
- Efficiency. By separating the configuration change event from the code that processes it we can avoid unnecessary calls. (E,g, if a property is removed before the added event is processed then neither event needs to be processed).
- Maintainability. Having the code separated into files by functionality makes it easier to find and understand than having it spread out through builders that are separated hierarchically.

#### Cons

- They add overhead and will be slower in many cases.
- Authoring them requires better understanding of how model building works
