### ISSUE TITLE
Document how EF and database cascade behaviors work together

### ISSUE THREAD

**Issue by rgamage** [dotnet/EntityFramework.Docs#828]
This entire article is about the impact of various OnDelete behaviors, but nowhere on this page is any instruction or example of how to set up / configure this behavior!  This is essential information.  We need examples, like:
```C#
            modelBuilder.Entity<BlogPost>()
                .HasOne(l => l.Blog)
                .WithMany(m => m.BlogPosts)
                .OnDelete(DeleteBehavior.Restrict);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed1b8a1-fa32-e147-ae0f-76b3620473f9
* Version Independent ID: 10ce2d9f-8284-a509-5fed-669abfb9d8ae
* Content: [Cascade Delete - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete)
* Content Source: [entity-framework/core/saving/cascade-delete.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/cascade-delete.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by vmkbagci** [comment]
I have a question regarding the necessity of using Include(), ThenInclude() while retrieving the entity to delete. 

Say I have a School with many Students and Student reference School back through a Foreign Key in the DB. 

If I do, 

var school = context.Schools.FirstOrDefault(s => s.Id == 1);

and then try to use context.Remove(school), it fails, throwing an exception about violation of Foreign Key requirements. In other words, the Students are not cascading deleted. If on the other hand, I use

var school = context.Schools.Include(s => s.Students).FirstOrDefault(s => s.Id == 1);

it works and deletes School along with its Students.

It is not a big deal to use Include(...) but it is bothering because I may later have a Disctrict with many Schools. If I want to delete the Destrict, I have to use

var destrict = context.Destricts.Include(d => d.Schools).ThenInclude(s => s.Students).FirstOrDefault(...)

You see that this will become quickly troublesome if we start adding child relations under Student (e.g. Grade, Class, etc.)

What are my options?

**Comment by ajcvickers** [comment]
@rgamage The API is documented here: https://docs.microsoft.com/en-us/ef/core/modeling/relationships#cascade-delete-1 but I agree this should be easier to find from this page.

@vmkbagci  Usually this is handled using cascade delete setup in the database. By default, Migrations will create a database that has cascade deletes configured. This means that dependents will be deleted by the database when the principal is deleted, even if the dependents are not loaded into the context.

**Comment by Alleno** [comment]
Would it be possible to specify cascade delete on a per-transaction basis instead of at the database definition level?

**Comment by ajcvickers** [comment]
@Alleno Do you know which databases support this and what the SQL looks like?

**Comment by itanex** [comment]
Bump.

While the page that @ajcvickers linked to explains the HOW to define the OnDelete behavior, this page really should illustrate the model builder should be for each of these scenarios. The page does do a good job explaining the effect but not the actual how for each scenario. The demo code also lacks illustrating each scenario and only covers the basic Cascade scenario.

Does the Blog or the Post get the OnDelete declaration?
