### ISSUE TITLE
Document when indexes are clustered or not

### ISSUE THREAD

**Issue by divega** [dotnet/EntityFramework.Docs#878]
Helpfulness rating is very low.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f85ea32c-8d23-d61d-6036-cd772e3e95d9
* Version Independent ID: 25dd8ac4-2521-5200-0ddf-63ac8c83787a
* Content: [Indexes - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/indexes)
* Content Source: [entity-framework/core/modeling/indexes.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/indexes.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by Alleno** [comment]
I'd like to understand what EF uses to build a clustered index. I heard that you shouldn't use a Guid for a clustered index, but does EF automatically create a clustered index using the primary key?

**Comment by tdykstra** [comment]
Closing this issue: on 10/10/18 SkyRay showed 4k page views and 0 ratings for the last 30 days. The number of ratings is not enough to draw reliable conclusions; when we do the next sweep for high-traffic/low ratings docs, we can reopen this one if this doc meets those criteria.

**Comment by ArwynFr** [comment]
@Alleno, EFCore will always use the Key propery/properties as the clustered index, so they removed the IsClustered property from indexes. Indexes will always be non-clustered, since only the Key can be clustured. However, what you want to achieve is available in EFCore via AlternateKeys.

AlternateKeys are non-clustered read-only properties that can be used as relationship target by EFCore. So instead of trying to create a clustered index and using the key as the relationship target, you should set your clustered index as Key and your relationship targets as AlternateKey. Note that EFCore also supports composite alternate keys.

Source : https://docs.microsoft.com/en-us/ef/core/modeling/alternate-keys
